<?php
 
/**
 * Implements hook_field_info().
 */
function custom_field_field_info() {
  return array(
    'url' => array(
      'label' => t('Url'),
      'description' => t('The resource url.'),
      'default_widget' => 'url_widget',
      'default_formatter' => 'url_formatter',
    ),
  );
}
 
/**
 * Implements hook_field_formatter_info().
 */
function custom_field_field_formatter_info() {
  return array(
      'url_formatter' => array(
          'label' => t('Url'),
          'field types' => array('url'),
      ),
  );
}
 
 
/**
 * Implements hook_field_formatter_view().
 * opgeroepen als content toegevoegd is en de pagina gerenderd w
 */
function custom_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  echo "<script>alert('custom_field_field_formatter_view entered')</script>";
  switch ($display['type']) {
    case 'url_formatter':
	  echo "<script>alert('case url_formatter test')</script>";
      foreach ($items as $delta => $item) {
           if ($item['url']) {
                //$formattedDate = _dateToString($item['custom_field']);
                //$element[$delta]['#markup'] = '<span>' . $formattedDate .'</span>';
				//$element[$delta]['#markup'] = '<span>' . $item['url'] .'</span>';
				$element[$delta]['#markup'] = '<span>' . 'hallo' .'</span>';
            }
      }
      break;
  }
  return $element;
}
 
/**
 * Implements hook_field_widget_form().
 * wordt uitgevoerd nadat field toegevoegd wordt aan content type en er opties van het veld ingesteld worden
 * en als je op add content van dit nieuwe content type klikt
 */
function custom_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
 
  echo "<script>alert('widget_form entered')</script>";
  switch ($instance['widget']['type']) {
    case 'url':
	  echo "<script>alert('case url')</script>";
      $element['url'] = array(
          '#type' => 'text',
          '#title' => $element['#title'],
          '#description' => $element['#description'],
          //'#default_value' => $news_data_value,
          //'#required' => $element['#required'],
		  '#required' => TRUE,
          //'#weight' => isset($element['#weight']) ? $element['#weight'] : 0,
          '#delta' => $delta,
          //'#element_validate' => array('strToDateValidate'),
      );
	case 'custom_field':
	  echo "<script>alert('case custom_field')</script>";
      $element['url'] = array(
          '#type' => 'text',
          '#title' => $element['#title'],
          '#description' => $element['#description'],
          //'#default_value' => $news_data_value,
          //'#required' => $element['#required'],
		  '#required' => TRUE,
          //'#weight' => isset($element['#weight']) ? $element['#weight'] : 0,
          '#delta' => $delta,
          //'#element_validate' => array('strToDateValidate'),
      );
 
      break;
  }
  return $element;
}
 
/**
 * Implements hook_field_widget_error().
 */
function custom_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'url_invalid':
      form_error($element, $error['message']);
      break;
  }
}
 
 
/**
 * Implements hook_field_is_empty().
 */
function custom_field_field_is_empty($item, $field) {
   if (empty($item['url'])) {
        return true;
   }
}
 
/**
 * Implements hook_field_widget_info().
 */
function custom_field_field_widget_info() {
  return array(
    'custom_field_url' => array(
      'label' => t('Url'),
      'field types' => array('url'),
    ),
  );
}