<?php

///////////
// BLOCK //
///////////

/**
 * Implements hook_block_info().
 * Geeft informatie over de block die de module aanbiedt
 */
function totaal_uren_block_info() {
	$blocks['user_custom'] = array(
		'info' => t('Blok met de huidige stand van de uren van de logging'),
	);
	return $blocks;
}

/**
 * Implements hook_block_info().
 * Definieert de titel en inhoud van de block
 */
function totaal_uren_block_view($delta='') {
	$block = null;
	$block['subject'] = 'Huidige stand uren';
	$block_content = null;
	$kobe = "SELECT SUM(TIME_TO_SEC(TIMEDIFF(EIND, BEGIN)))/3600 'uren' FROM webform_views_logging_5 where NAAM = 'Kobe'";
	$stef = "SELECT SUM(TIME_TO_SEC(TIMEDIFF(EIND, BEGIN)))/3600 'uren' FROM webform_views_logging_5 where NAAM = 'Stef'";
	$uren_kobe = 0;
	$uren_stef = 0;
	$result = db_query($kobe);
	foreach($result as $record){
		$uren_kobe = $record->uren;
	}
	$result = db_query($stef);
	foreach($result as $record){
		$uren_stef = $record->uren;
	}
	$block_content .= "<table><th class='views-field views-field-Beschrijving' ></th><th class='views-field views-field-Beschrijving' >Aantal uren</th><tr><td>Kobe</td><td>";
	$block_content .= $uren_kobe;
	$block_content .= "</td></tr><tr><td>Stef</td><td>";
	$block_content .= $uren_stef;
	$block_content .= "</td></tr><tr><td>Totaal</td><td>";
	$block_content .= $uren_kobe+$uren_stef;
	$block_content .= "</td></tr></table>";
	$block['content'] = $block_content;
	return $block;
}