<?php
/*
	Title: CoAP library
	Author: Kobe Wright
	
*/


//////////////////////////////////////////////////////////////////////////////////////////
//																						//
//									SUPPORTED FUNCTIONS									//
//									-------------------									//
//																						//
//	- coap_library_generate_message_id()												//
//	- coap_library_generate_token($token_length)										//
//	- coap_library_generate_header_and_token($type, $method, $token)					//
//	- coap_library_add_option($message, $option_number, $value)							//
//	- coap_library_add_payload($message, $payload)										//
//	- coap_library_string_to_hex_with_padding($string)									//
//	- coap_library_string_to_hex_without_padding($string)								//
//	- coap_library_hex_to_string($hex)													//
//	- coap_library_generate_observe_get_request($uri_path)								//
//	- coap_library_generate_basic_get_request($uri_path)								//
//	- coap_library_get_option_value($message, $option_number)							//
//	- coap_library_get_max_age($message)												//
//	- coap_library_get_payload($message)												//
//	- coap_library_get_message_id_from_message($message)								//
//	- coap_library_generate_acknowledgement($message)									//
//	- coap_library_generate_reset($response)											//
//	- coap_library_hex_to_binary($hex)													//
//	- coap_library_get_bit_from_hex($hex, $bit_number)									//
//	- coap_library_send_get_request($ip, $resource)										//
// 	- coap_library_increment_hex(&$hex)													//
//																						//
//////////////////////////////////////////////////////////////////////////////////////////

require_once('coap_library_classes.inc');


//////////////////////////////////////////////////////////////////////////////////////////
// Convert normal string to hexadecimal string, padding when nr of characters is uneven //
//////////////////////////////////////////////////////////////////////////////////////////
function coap_library_string_to_hex_with_padding($string){
    $hex='';
	$string = '' . $string;
    for ($i=0; $i < strlen($string); $i++){
		$byte = dechex(ord($string[$i]));
		if(strlen($byte) == 1){
			$byte = "0" . $byte;
		}
        $hex .= $byte;
    }
    return $hex;
}


/////////////////////////////////////////////////////////////
// Convert normal string to hexadecimal string, no padding //
/////////////////////////////////////////////////////////////
function coap_library_string_to_hex_without_padding($string){
    $hex='';
	$string = '' . $string;
    for ($i=0; $i < strlen($string); $i++){
		$byte = dechex(ord($string[$i]));
		$hex .= $byte;
    }
    return $hex;
}


/////////////////////////////////////////////////
// Convert hexadecimal string to normal string //
/////////////////////////////////////////////////
function coap_library_hex_to_string($hex){
    $string='';
    for ($i=0; $i < strlen($hex)-1; $i+=2)
    {
        $string .= chr(hexdec($hex[$i].$hex[$i+1]));
    }
    return $string;
}


///////////////////////////////////////////////////
// Convert hexadecimal message to binary message //
///////////////////////////////////////////////////
function coap_library_hex_to_binary($hex){
	$binary = pack("H*", $hex);
	return $binary;
}


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Get bit with given number from a given hexadecimal value, returns null if bit number or hexadecimal value is invalid //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
function coap_library_get_bit_from_hex($hex, $bit_number){
	if($bit_number > 3 || $bit_number < 0 || strlen($hex) != 1){
		return null;
	}
	if($bit_number == 0){
		return (hexdec($hex) % 2);
	}
	else if($bit_number == 1){
		return (hexdec($hex) == 2 || hexdec($hex) == 3 || hexdec($hex) == 6 || hexdec($hex) == 7 || hexdec($hex) == 10 || hexdec($hex) == 11 || hexdec($hex) == 14 || hexdec($hex) == 15) ? 1 : 0;
	}
	else if($bit_number == 2){
		return ((hexdec($hex) > 3 && hexdec($hex) < 8) || (hexdec($hex) > 11 && hexdec($hex) < 16 )) ? 1 : 0;
	}
	else if($bit_number == 3){
		return (hexdec($hex) > 7) ? 1 : 0;
	}
	return null;
}

function coap_library_stop_observing($module, $uri){
	$num_deleted = db_delete('coap_library_observe_resources')
		->condition('uri', $uri, '=')
		->condition('module', $module, '=')
		->execute();
}

function coap_library_get_message_id_from_message($response){
	$message_id = substr($response, 4, 4);
	return $message_id;
}
//////////////////////////////////////////
// Increments hex value.				//
// return:								//
//			1 if length hex increases	//
//			0 if length stays the same	//
//////////////////////////////////////////
function coap_library_increment_hex(&$hex){
	$hex_length =  strlen($hex);
	$hex = dechex(hexdec($hex) + 1);
	$new_hex_length = strlen($hex);
	$dif = $hex_length - $new_hex_length;
	if($dif > 0){
		for ($i = 0; $i < $dif; $i++) {
			$hex = '0' . $hex;
		}
	}
	else if($dif < 0){
		$hex = substr($hex,1);
		return 1;
	}
	return 0;
}

//	Generates a message ID that isn't yet in use
//	Message ID's get incremented every time this function is called
//	Returns numeric message id
function coap_library_generate_message_id(){
	$current_message_id;
	if($cache = cache_get('current_message_id')){
		$current_message_id = $cache->data;
	}
	else{
		$current_message_id = rand(0, 65535);
	}
	$current_message_id++;
	$current_message_id % 65536;
	cache_set('current_message_id', $current_message_id, 'cache');
	return $current_message_id;
}

//	Generates a valid token with given length
//	Tokens get incremented with each function call
//	Returns token (hexadecimal string)
function coap_library_generate_token($token_length){
	if(!is_int($token_length)){
		return null;
	}
	$token = variable_get('current_token', null);
	if($cache = cache_get('current_token')){
		$current_token = $cache->data;
	}
	else{
		$current_token = rand(0, 65535);
	}
	$current_token++;
	$current_token % 65536;
	cache_set('current_token', $current_token, 'cache');
	$current_token = dechex($current_token);
	$token_string = strval($current_token);
	$token_string = str_pad($token_string, $token_length*2, "0", STR_PAD_LEFT);
	return substr($token_string, 0, $token_length*2);
}

//	Retrieves the numeric code of the given hexadecimal message
function coap_library_get_numeric_message_code_from_hex_message($hex_message){
	return hexdec(substr($hex_message, 2, 2));
}

//	Retrieves the payload, if present, from a given hexadecimal message
//	Returns null if no payload is present
//	Returns payload in hexadecimal form
function coap_library_get_payload_from_hex_message($hex_message){
	if(strlen($hex_message) < 8){
		return null;
	}
	$pos = strrpos($hex_message, 'ff', 0);
	if(!$pos){
		return null;
	}
	return substr($hex_message, $pos+2);
}

// Retrieves the max-age value, if present, from a given hexadecimal message
// Returns 0 if no max age option is included
function coap_library_get_max_age_from_hex_message($hex_message){
	$max_age_hex = $this->get_option_value_from_hex_message($hex_message, 14);
	if(!$max_age_hex){
		return 0;
	}
	return hexdec($max_age_hex);
}

// Extracts the hexadecimal value of the option with given number from a hexadecimal message
// Returns -1 if the option with given number is not present
function coap_library_get_option_value_from_hex_message($hex_message, $option_number){
	$follow_up = $hex_message . "\r\n";
	if(strlen($hex_message) < 8){
		return -1;
	}
	$token_length = hexdec(substr($hex_message, 1, 1));
	if(strlen($hex_message) < 8+($token_length*2)){
		return -1;
	}
	$pos = 8 + ($token_length*2);
	$current_number = 0;
	if($pos < strlen($hex_message)){
		$extra = 0;
		$option_delta = hexdec(substr($hex_message, $pos, 1));
		if($option_delta == 13){
			$option_delta = hexdec(substr($hex_message, $pos+2, 2))-13;
			$extra += 2;
		}
		else if($option_delta == 14){
			$option_delta = hexdec(substr($hex_message, $pos+2, 4))-269;
			$extra += 4;
		}
		$option_length = hexdec(substr($hex_message, $pos+1, 1));
		if($option_length == 13){
			$option_length = hexdec(substr($hex_message, $pos+2+$extra, 2))-13;
			$extra += 2;
		}
		else if($option_length == 14){
			$option_length = hexdec(substr($hex_message, $pos+2+$extra, 4))-269;
			$extra += 4;
		}
		$option_length *= 2;
	}
	while($pos < strlen($hex_message) && $option_number > $current_number + $option_delta){
		$follow_up .= "nr: " . ($current_number + $option_delta) . ", length: " . $option_length . "; ";
		$current_number += $option_delta;
		$pos += 2 + $extra + $option_length;
		if($pos < strlen($hex_message)){
			$extra = 0;
			$option_delta = hexdec(substr($hex_message, $pos, 1));
			if($option_delta == 13){
				$option_delta = hexdec(substr($hex_message, $pos+2, 2))-13;
				$extra += 2;
			}
			else if($option_delta == 14){
				$option_delta = hexdec(substr($hex_message, $pos+2, 4))-269;
				$extra += 4;
			}
			$option_length = hexdec(substr($hex_message, $pos+1, 1));
			if($option_length == 13){
				$option_length = hexdec(substr($hex_message, $pos+2+$extra, 2))-13;
				$extra += 2;
			}
			else if($option_length == 14){
				$option_length = hexdec(substr($hex_message, $pos+2+$extra, 4))-269;
				$extra += 4;
			}
			$option_length *= 2;
		}
	}
	$follow_up .= "nr: " . ($current_number + $option_delta) . ", length: " . $option_length;
	if($pos > strlen($hex_message) || $option_number != $current_number + $option_delta){
		return -1;
	}
	return substr($hex_message, $pos+2+$extra, $option_length);
}

//	Adds an option with given number and value to the given hexadecimal message
//	Expects the given option value to be a normal ASCII string or decimal, not hexadecimal
//	Returns null if message is smaller than 4 bytes
//	IMPORTANT: options MUST be added in order of growing option deltas
function coap_library_add_option_to_hex_message(&$hex_message, $option_number, $value){
	if(strlen($hex_message) < 8){
		return null;
	}
	$token_length = hexdec(substr($hex_message, 1, 1));
	if(strlen($hex_message) < 8 + ($token_length*2)){
		return null;
	}
	//pointer pos goedzetten om volgende optie toe te voegen
	$pos = 8 + ($token_length*2);
	$current_number = 0;
	$option_delta = hexdec(substr($hex_message, $pos, 1));
	while($pos < strlen($hex_message) && $option_number >= $current_number + $option_delta){
		$extra = 0;
		if($option_delta == 13){
			$option_delta = hexdec(substr($hex_message, $pos+2, 2))-13;
			$extra += 2;
		}
		else if($option_delta == 14){
			$option_delta = hexdec(substr($hex_message, $pos+2, 4))-269;
			$extra += 4;
		}
		$option_length = hexdec(substr($hex_message, $pos+1, 1));
		if($option_length == 13){
			$option_length = hexdec(substr($hex_message, $pos+2+$extra, 2))-13;
			$extra += 2;
		}
		else if($option_length == 14){
			$option_length = hexdec(substr($hex_message, $pos+2+$extra, 4))-269;
			$extra += 4;
		}
		$option_length *= 2;
		$current_number += $option_delta;
		$pos += 2 + $extra + $option_length;
		if($pos < strlen($hex_message)){
			$option_delta = hexdec(substr($hex_message, $pos, 1));
		}
	}
		
	$value_length = strlen($value)/2;
	
	$mid = null;
	// Add Option Delta
	if($option_number-$current_number > 268){
		$mid .= "e";
	}
	else if($option_number-$current_number > 13){		
		$mid .= "d";
	}
	else{
		$mid .= dechex($option_number-$current_number);
	}
	
	// Add Option Length
	if($value_length > 268){
		$mid .= "e";
	}
	else if($value_length > 13){
		$mid .= "d";
	}
	else{
		$mid .= dechex($value_length);
	}
	
	// Add optional extended Option Delta
	if($option_number-$current_number > 268){
		$temp = coap_library_string_to_hex_with_padding($option_number-269-$current_number);
		str_pad($temp, 4, "0", STR_PAD_LEFT);
		$mid .= $temp;
	}
	else if($option_number-$current_number > 12){
		$temp = coap_library_string_to_hex_with_padding($option_number-13-$current_number);
		str_pad($temp, 2, "0", STR_PAD_LEFT);
		$mid .= $temp;
	}
	
	// Add optional extended Option Length
	if($value_length > 268){
		$temp = coap_library_string_to_hex_with_padding($value_length-269);
		str_pad($temp, 4, "0", STR_PAD_LEFT);
		$mid .= $temp;
	}
	else if($value_length > 12){
		$temp = coap_library_string_to_hex_with_padding($value_length-13);
		str_pad($temp, 2, "0", STR_PAD_LEFT);
		$mid .= $temp;
	}
	// Add Option Value
	$mid .= $value;
	
	if($pos >= strlen($hex_message)){
		$hex_message .= $mid;
	}
	else{
		$start = substr($hex_message, 0, $pos);
		$end = substr($hex_message, $pos);
		$hex_message = $start . $mid . $end; // nog rekening houden met eventueel extra option delta veld en extra option length veld
	}
}

// 	Adds a payload to the given message, if not yet present
//	Returns null if the message is shorter than 4 bytes or if the message already has a payload
function coap_library_add_payload_to_hex_message(&$hex_message, $payload){
	if(strlen($hex_message) < 8){
		return null;
	}
	if(strpos($hex_message, 'ff', 0)){
		return null;
	}
	if($payload != '' && $payload != null){
		$hex_message .= 'ff' . $payload;
	}
}

//	Retrieves the textual representation of the code of the given hexadecimal message
function coap_library_get_message_code_from_hex_message($hex_message){
	$constants = new CoAPConstants();
	
	$code_nr = hexdec(substr($hex_message, 2, 2));
	return $constants->response_code_mapping[$code_nr];
}

//	Retrieves the numeric type of the given hexadecimal message
//	Return null if type is invalid
function coap_library_get_numeric_type_from_hex_message($hex_message){
	$hex = substr($hex_message, 0, 1);
	switch ($hex) {
		case "4":
			return 0;
			break;
		case "5":
			return 1;
			break;
		case "6":
			return 2;
			break;
		case "7":
			return 3;
			break;
		default:
			return null;
	}
}

//	Retrieves the token length from a given hexadecimal message
function coap_library_get_token_length_from_hex_message($hex_message){
	return hexdec(substr($hex_message, 1, 1));
}

//	Retrieves the token from a given hexadecimal message
function coap_library_get_token_from_hex_message($hex_message){
	$token_length = intval(coap_library_get_token_length_from_hex_message($hex_message));
	return substr($hex_message, 8, $token_length*2);
}
