<?php

require_once(drupal_get_path('module', 'coap_library') . '/coap_library_classes.inc');

// This hook is invoked during node viewing after the node is fully loaded
function node_content_view($node, $view_mode) {
	if($node->type == 'coap_sensors'){
		$node->content['coap_sensors_form'] = drupal_get_form('coap_sensors_form', $node);
	}
	return $node;
}

/**
 * Implements hook_menu().
 * Creëert het pad waarnaar jQuery een ajax call kan uitvoeren en de callback-functie
 */
function coap_sensors_menu() {
  $items = array();
  $items["coap_sensors/discover"] = array(
    "title" => "Discovery",
    "page callback" => "coap_sensors_discover_callback",
    "access callback" => true,
    "type" => MENU_CALLBACK
  );
  $items["coap_sensors/observe"] = array(
    "title" => "Get last entry",
    "page callback" => "coap_sensors_observe_callback",
    "access callback" => true,
    "type" => MENU_CALLBACK
  );
  return $items;
}

function coap_sensors_discover_callback(){
	$output ='';
	
	if($user->uid != 0 && !isset($_SESSION['links'])){
		$result = db_select('coap_sensors_link_users','user_device')
				->fields('user_device', array('uid','device_uri'))
				->condition('uid', $user->uid, '=')
				->execute();
		foreach($result as $record){
			$device_uri = $record->device_uri;
		}
		
		$result = db_select('coap_sensors_core_links', 'links')
				->fields('links', array('device_uri','link_name','title'))
				->condition('device_uri', $device_uri, '=')
				->execute();
		foreach($result as $record){
			$output .= '<link>';
			$output .= '<link_name>';
			$output .= $record->link_name;
			$output .= '</link_name>';
			$output .= '<title>';
			$output .= $record->title;
			$output .= '</title>';
			$output .='</link>';
		}
	}	
	else{
		for($i=0 ; $i<count($_SESSION['links']) ; $i++){
			$output .= '<link>';
			$output .= '<link_name>';
			$output .= $_SESSION['links'][$i]['link_name'];
			$output .= '</link_name>';
			$output .= '<title>';
			$output .= $_SESSION['links'][$i]['title'];
			$output .= '</title>';
			$output .='</link>';
		}
	}
	
	print $output;
}

// Functie die wordt uitgevoerd als een ajax call wordt uitgevoerd naar /coap_sensors/observe, geeft de laatste entry terug
function coap_sensors_observe_callback(){
	global $user;
	
	// bekeken URI bepalen
	$query = db_select('CoAP_users', 'users');
	$query
		->fields('users', array('uid', 'uri', 'watch', 'last_response', 'last_method', 'responded', 'response_type'))
		->condition('uid', $user->uid, '=')
		->condition('watch', 1, '=')
		->range(0,1);
	$result = $query->execute();
	$uri = '';
	foreach($result as $record){
		$uri = $record->uri;
		$method = $record->last_method;
		$response = $record->last_response;
		$responded = $record->responded;
		$response_type = $record->response_type;
	}
	
	// Laatste opvraging ophalen
	$query = db_select('CoAP_values', 'coap_values');
	$query
		->fields('coap_values', array('hid', 'uid', 'timestamp', 'max_age', 'parsed_value', 'uri'))
		->condition('uri', $uri, '=')
		->condition('uid', $user->uid, '=')
		->orderBy('hid', 'DESC')
		->range(0,1);
	$result = $query->execute();
	
	// print een rij uit in tabelformaat zodat jQuery die kan gebruiken om in de tabel te stoppen
	foreach ($result as $record){
		$resources_query = db_select('CoAP_resources', 'resources');
		$resources_query
			->fields('resources', array('uri', 'last_error'))
			->condition('uri', $record->uri, '=');
		$resources_result = $resources_query->execute();
		
		foreach($resources_result as $resources_record){
			$output = "<error>" . $resources_record->last_error . "</error><responded>" . $responded . "</responded><get_response>" . $response . "</get_response><method>" . $method . "</method><response_type>" . $response_type . "</response_type>";
			$hid = $record->hid;
			$timestamp = $record->timestamp;
			$temperatuur = $record->parsed_value;
			$max_age = $record->max_age;
			$output .= "<tr><td>" . $hid . "</td><td>" . $temperatuur . "</td><td>" . $max_age . "</td><td>" . $timestamp . "</td></tr>";
		}
	}
	if(!isset($output)){
		$query = db_select('CoAP_resources', 'resources');
		$query
			->fields('resources', array('uri', 'last_error'))
			->condition('uri', $uri, '=');
		$result = $query->execute();
		
		if($result->rowCount() > 0){
			foreach($result as $record){
				$output = "<error>" . $record->last_error . "</error><responded>" . $responded . "</responded><get_response>" . $response . "</get_response><method>" . $method . "</method><response_type>" . $response_type . "</response_type>";
			}
		}
		else{
			$output = "no values";
		}
	}
	
	// Responded op false zetten
	$num_updated = db_update('CoAP_users')
		->fields(array(
			'responded' => 0,
		))
		->condition('uid', $user->uid, '=')
		->execute();
	
	print $output;
}

/**
 * Returns the list of steps and their associated forms.
 *
 * @return $array
 */
function _form_example_steps() {
  return array(
      1 => array(
        'form' => 'coap_sensors_form_core',
      ),
      2 => array(
        'form' => 'coap_sensors_form_resource',
      ),
    );
}

/**
 * Submit handler for the "previous" button.
 * - Stores away $form_state['values']
 * - Decrements the step counter
 * - Replaces $form_state['values'] with the values from the previous state.
 * - Forces form rebuild.
 */
function coap_sensors_back_to_core_submit($form, &$form_state) {
  $current_step = &$form_state['step'];
  $form_state['step_information'][$current_step]['stored_values'] = $form_state['values'];
  if ($current_step > 1) {
    $current_step--;
    $form_state['values'] = $form_state['step_information'][$current_step]['stored_values'];
  }
  $form_state['rebuild'] = TRUE;
}

/**
 * Submit handler for the 'next' button.
 * - Saves away $form_state['values']
 * - Increments the step count.
 * - Replace $form_state['values'] from the last time we were at this page
 *   or with array() if we haven't been here before.
 * - Force form rebuild.
 *
 * @param $form
 * @param $form_state
 */
function coap_sensors_select_resource_submit($form, &$form_state) {
	$link = $_SESSION['links'][$form_state['values']['table']];
	
	$current_step = &$form_state['step'];
	$form_state['step_information'][$current_step]['stored_values'] = $form_state['values'];

	if ($current_step < count($form_state['step_information'])) {
		$current_step++;
		if (!empty($form_state['step_information'][$current_step]['stored_values'])) {
			$form_state['values'] = $form_state['step_information'][$current_step]['stored_values'];
		}
		else {
			$form_state['values'] = array();
		}
		$form_state['values']['link'] = $link;
		//dpm($form_state['values']['link']);
		$form_state['rebuild'] = TRUE;  // Force rebuild with next step.
		return;
	}
}

/**
 * The primary formbuilder function. This is the form that
 * you should call with drupal_get_form() from your code, and it will include
 * the rest of the step forms defined.
 *
 * This form has two defined submit handlers to process the different steps:
 *  - Previous: handles the way to get back one step in the wizard.
 *  - Next:     handles each step form submission,
 *
 * The third handler, the finish button handler, is the default form _submit
 * handler used to process the information.
 */
function coap_sensors_form($form, &$form_state) {
	drupal_add_js('https://www.google.com/jsapi'); // JavaScript bestand toevoegen
	drupal_add_js(drupal_get_path('module', 'coap_sensors') . '/js/coap_sensors.js'); // JavaScript bestand toevoegen
	
	if (empty($form_state['step'])) {
		$form_state['step'] = 1;
		
		// This array contains the function to be called at each step to get the
		// relevant form elements. It will also store state information for each
		// step.
		$form_state['step_information'] = _form_example_steps();
	}
	
	$step = &$form_state['step'];
	//drupal_set_title(t('Sensor network: Step @step', array('@step' => $step)));
	
	// Call the function named in $form_state['step_information'] to get the
	// form elements to display for this step.
	$form = $form_state['step_information'][$step]['form']($form, $form_state);
	
	// Show the 'previous' button if appropriate. Note that #submit is set to
	// a special submit handler, and that we use #limit_validation_errors to
	// skip all complaints about validation when using the back button. The
	// values entered will be discarded, but they will not be validated, which
	// would be annoying in a "back" button.
	if ($step > 1) {
		$form['prev'] = array(
			'#type' => 'submit',
			'#value' => t('Core'),
			'#name' => 'prev',
			'#submit' => array('coap_sensors_back_to_core_submit'),
			'#limit_validation_errors' => array(),
		);
	}

	// Show the Next button only if there are more steps defined.
	if ($step < count($form_state['step_information'])) {
		// The Next button should be included on every step
		$form['next'] = array(
			'#type' => 'submit',
			'#value' => t('Select'),
			'#name' => 'next',
			'#submit' => array('coap_sensors_select_resource_submit'),
		);
	}
	else {
		// Just in case there are no more steps, we use the default submit handler
		// of the form wizard. Call this button Finish, Submit, or whatever you
		// want to show. When this button is clicked, the
		// form_example_wizard_submit handler will be called.
		// $form['finish'] = array(
			// '#type' => 'submit',
			// '#value' => t('Finish'),
		// );
	}

	// Include each validation function defined for the different steps.
	if (function_exists($form_state['step_information'][$step]['form'] . '_validate')) {
		$form['next']['#validate'] = array($form_state['step_information'][$step]['form'] . '_validate');
	}

	return $form;
}

function build_headers(){
return array
  (
    // 'link_name' => t('link name'),	
	// 'rt' => t('application-specific semantic type'),
	// 'ct' => t('content-type'),
	// 'if' => t('interface desciption'),
	// 'sz' => t('maximum size'),
	// 'title' => t('human-readable name'),
	// 'anchor' => t('anchor'),
	// 'rel' => t('rel'),
	
	'link_name' => t('link name'),
	'title' => t('human-readable name'),
  );
}

function build_options($links){
  $options = array();
  foreach($links as $link)
  {
    $options[$link['uid']] = array // each element of the array is keyed with the UID
    (
		// 'link_name' => $link['link_name'],
		// 'rt' => $link['rt'],
		// 'ct' => $link['ct'],
		// 'if' => $link['if'],
		// 'sz' => $link['sz'],
		// 'title' => $link['title'],
		// 'anchor' => $link['anchor'],
		// 'rel' => $link['rel'],	
		
		'link_name' => $link['link_name'],
		'title' => $link['title'],
	);
  }
  return $options;
}

/**
 * Custom validation form for the core page.
 */
function coap_sensors_form_core_validate($form, &$form_state) {
	$regex = '/^(((?=(?>.*?(::))(?!.+\3)))\3?|([\dA-F]{1,4}(\3|:(?!$)|$)|\2))(?4){5}((?4){2}|(25[0-5]|(2[0-4]|1\d|[1-9])?\d)(\.(?7)){3})\z/i';
	if(!preg_match($regex, $form_state['values']['device_uri'], $matches)){
		form_set_error('device_uri', t('Please enter a valid IPv6-adres.'));
	}
}

/**
 * Returns form elements for core page. This is the
 * first step.
 */
function coap_sensors_form_core($form, &$form_state) {
	global $user;
	
	//textfield for device uri
	$form['device_uri'] = array
	(
		'#type' => 'textfield',
		'#title' => t('Device IPv6 adress'),
		'#size' => 60,
		'#required' => TRUE,
	);
	//dpm($_SESSION);
	
	// if($user->uid != 0 && !isset($_SESSION['links']))
		// dpm('db');
	// else
		// dpm('cache');
	
	// if(isset($_SESSION['links'])){
		// dpm($_SESSION['links']);
		// drupal_set_message($_SESSION['links']);
	// }
	// else{
		// drupal_set_message('geen sessie');
	// }
	
	if($user->uid != 0){ //anonieme user	
		$_SESSION['links'] = array();	
		$result = db_select('coap_sensors_link_users','user_device')
				->fields('user_device', array('uid','device_uri'))
				->condition('uid', $user->uid, '=')
				->execute();
		foreach($result as $record){
			$device_uri = $record->device_uri;
			$form['device_uri']['#default_value'] = $device_uri;		
			$result = db_select('coap_sensors_core_links', 'links')
				->fields('links', array('device_uri','link_name','title'))
				->condition('device_uri', $device_uri, '=')
				->execute();
			$links = array();
			foreach($result as $record){
				$link = array();
				$link['link_name'] = $record->link_name;
				$link['title'] = $record->title;
				array_push($links,$link);
			} 		
			$_SESSION['links'] = $links;
		}
	}

	//button to reload the well-know/core
	$form['reload_device'] = array
	(
		'#type' => 'submit',
		'#value' => t('Reload device'),
		'#submit' => array('reload_device_core'),
	);
	
	//button to clear tableselect
	$form['clear_tableselect'] = array
	(
		'#type' => 'submit',
		'#value' => t('Clear'),
		'#attributes' => array('id' => 'core_table'),
		'#submit' => array('clear_tableselect'),
	);	

	$form['tableselect_container'] = array(
		'#type' => 'container',
		'#attributes' => array(
			'class' => array('class-name'),
		),
	);
	
	$links = array();
	
	//build headers
	$header = build_headers();
	
	//build options
	$options = build_options($links);
	
	$table = array
	(
		'#type' => 'tableselect',
		'#header' => $header,
		'#options' => $options,
		//'#empty' => t('No sensors found'),
		'#multiple' => FALSE,
	);
	
	if($user->uid != 0 && $result->rowCount() != 0)
		$table['#empty'] = 'Fetching sensors...';
	else		
		$table['#empty'] = 'Enter a URI and click on \'Reload device\' to display resources here.';
	
	$form['tableselect_container']['table']= $table;
  
	// $form['select'] = array
	// (
		// '#type' => 'submit',
		// '#value' => t('Select'),
		// '#submit' => array('show_sensor'),
	// );
	
	for($i=0 ; $i<0 ; $i++){
		dpm(variable_get("response_string_$i",0));
		//dpm(variable_get("response_string_$i",0));
		//dpm($i . ': ' . variable_get("discovery_request_$i", 0) . ' gelijk aan 4? ' . variable_get("next_length_$i",0));
		//dpm(variable_get("response_string_$i",0));
		//dpm(variable_get("response_hex_string_$i",0));
		//dpm(variable_get("option23_$i",0));
		//dpm(variable_get("bool_response_$i",0));
		//dpm(variable_get("has_next_$i", 0));
		//dpm(variable_get("has_next_$i", 0) . '|' . variable_get("message_id_$i", 0) . '|' . variable_get("message_id_next_$i", 0));
		//dpm('---------------------------------------------------');
	}
	
	//2001:6a8:1d80:200::2
	
	// drupal_add_js('https://www.google.com/jsapi'); // JavaScript bestand toevoegen
	// drupal_add_js(drupal_get_path('module', 'coap_sensors') . '/js/sensor.js'); // JavaScript bestand toevoegen
	
	return $form;
}

//submit handler when clicked on reload device
function reload_device_core($form, &$form_state) {
	$_SESSION['device_uri'] = $form_state['values']['device_uri'];
	//dpm('reload submit');
	//background_process_start('start_discover', $form_state['values']['device_uri']);  
	start_discover($form_state['values']['device_uri']); //voorgrond
	$form_state['rebuild'] = TRUE;
}

//submit handler when clicked on reload device
function clear_tableselect($form, &$form_state) {
	global $user;
	if($user->uid!=0){
		db_delete('coap_sensors_link_users')
			->condition('uid', $user->uid, '=')
			->execute();
	}
	$_SESSION['links'] = array();
	$form_state['rebuild'] = TRUE;
}

function start_discover($ip){
	$coap_factory = new CoAPMessageFactory('coap_sensors', $ip, '');
	$response_obj = null;
	$payloads = '';
	$has_more = true;
	while($has_more){
		$coap_message = $coap_factory->create_discovery_request($response_obj);
		$response_obj = $coap_message->send_message();
		if($response_obj){
			$option_value = $response_obj->get_option_value(23);
			if($option_value != -1){
				$has_more = coap_library_get_bit_from_hex(substr($option_value,strlen($option_value)-1,1),3);
				$payloads .= $response_obj->get_payload();
			}
			else $has_more = false;
		}
		else $has_more = false;
	}
	parse_discovery_payloads($ip,$payloads);
}

function parse_discovery_payloads($ip,$payloads){
	//dpm('payload geparsed');
	global $user;
	$links = array();
	$regex = '/<[^>]+>\s*(;\s*\w+\s*(=\s*(\w+|"[^"]*(\\.[^"]*)*")\s*)?)*/';
	preg_match_all($regex, $payloads, $resources);
	
	if($user->uid != 0){
		db_delete('coap_sensors_link_users')
				->condition('uid', $user->uid, '=')
				->execute();
		
		$query = db_delete('coap_sensors_core_links')
			->condition('device_uri', $ip, '=')
			->execute();
	}
	$id=-1;
	for($i=0 ; $i < count($resources[0]) ; $i++){
		if(preg_match('/^<([^>\?]+)[^>]*>\s*(;.+)?\s*$/', $resources[0][$i], $elements)){ //tweede nul moet $i zijn
			$uri = $elements[1];
			if (preg_match('/[a-zA-Z]+:\/\/[^\/]+.*/', $uri, $bin)) {
				// absolute URI, correct
			} else {
				// fix for old Contiki implementation and others which omit the leading '/' in the link format
				if (substr($uri,0,1)!='/') $uri = '/' . $uri;
			}
			if($elements[2]){
				preg_match_all('/;\s*\w+\s*(=\s*(\w+|"([^"]*(\\.[^"]*)*)"))?/',$elements[2],$tokens);
				
				$attributes = array(
					'device_uri' => $ip,
					'link_name' => $uri,
				);
				$link = array();
				$link['link_name'] = $uri;
				for($e=0 ; $e<count($tokens[0]) ; $e++){
					preg_match('/;\s*([^<"\s;,=]+)\s*(=\s*(([^<"\s;,]+)|"([^"]*(\\.[^"]*)*)"))?/',$tokens[0][$e],$keyvalues);
					if($keyvalues[1] != 'if') $attribute = $keyvalues[1];
					else $attribute = $keyvalues[1] . 'd';
					$attributes[$attribute] = (count($keyvalues)>2 ? ($keyvalues[4] ? $keyvalues[4] : $keyvalues[5]) : 1);
					
					$link[$attribute] = $attributes[$attribute];
				}
				array_push($links,$link);
			}
			
			if($user->uid != 0){			
				$id = db_insert('coap_sensors_core_links')
				->fields($attributes)
				->execute();
			}
		}
		else{
			//variable_set("response_string_$i", 'no match');
		}		
	}
	$_SESSION['links'] = $links;
	if($id != -1 && $user->uid != 0){ //tweede stuk is eigenlijk overbodig, maar je weet nooit
		$id = db_insert('coap_sensors_link_users')
			->fields(array(
				'uid' => $user->uid,
				'device_uri' => $ip,
				))
			->execute();
	}
}

/**
 * Returns form elements for the resource page. This is the
 * second step of the wizard.
 */
function coap_sensors_form_resource($form, &$form_state) {
	global $user;
	
	//hoe forms samenvoegen:
	//$extra = basic_address_form($form, $form_state);
	//$form = array_merge_recursive($form, $extra);
	
	$form = array_merge_recursive($form, uri_form($form, $form_state));
	$form = array_merge_recursive($form, observe_form($form, $form_state));
	$form = array_merge_recursive($form, bekijken_form($form, $form_state));
	$form = array_merge_recursive($form, get_request_form($form, $form_state));
	$form = array_merge_recursive($form, put_request_form($form, $form_state));
	$form = array_merge_recursive($form, post_request_form($form, $form_state));
	$form = array_merge_recursive($form, delete_request_form($form, $form_state));
	
	
	$device_uri = $_SESSION['device_uri'];
	$link = $form_state['values']['link'];
	
	dpm($device_uri);
	dpm($link);
	
	return $form;
}

//////////////////
// BEKIJKEN FORM //
//////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function bekijken_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('Observe'),
	);
	
	global $user;
	$query = db_select('coap_sensors_users', 'users');
	$query
		->fields('users', array('uid', 'uri', 'watch'))
		->condition('uid', $user->uid,'=');
	$result = $query->execute();
	
	// Radio buttons om URI te selecteren
	if($result->rowCount() > 0){
		$options = array();
		foreach ($result as $record){
			$options[$record->uri] = $record->uri;
			if($record->watch == 1){
				$uri = $record->uri;
			}
		}
		$form['bekijken']['uri'] = array(
			'#type' => 'radios',
			'#title' => t('Selecteer een resource'),
			'#default_value' => $uri, // Default value moet geselecteerde URI worden
			'#options' => $options,
		);
	}
	
	// Submit-knop
	$form['bekijken']['submit'] = array (
		'#type' => 'submit',
		'#value' => t("Bekijken"),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function bekijken_form_submit($form, $form_state) {
	global $user;
	
	// Variabele 'bekijken' van elk URI voor de user in de databank op 0 zetten
	$num_updated = db_update('coap_sensors_users')
		->fields(array(
			'watch' => 0,
		))
		->condition('uid', $user->uid, '=')
		->execute();
	
	// Als observen opgestart wordt, variabele 'bekijken' op 1 zetten voor de gekozen URI
	$num_updated = db_update('coap_sensors_users')
		->fields(array(
			'watch' => 1,
		))
		->condition('uid', $user->uid, '=')
		->condition('uri', $form_state['values']['uri'], '=')
		->execute();
}

//////////////////////
// GET REQUEST FORM //
//////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function get_request_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('GET Request'),
	);
	
	// Submit-knop
	$form['wx_info']['temperatuur_udp_url_submit'] = array (
		'#type' => 'submit',
		'#value' => t('GET'),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function get_request_form_submit($form, $form_state) {
	$handle = background_process_start('start_request', 'GET');
}

//////////////////////
// PUT REQUEST FORM //
//////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function put_request_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('PUT Request'),
	);
	
	// Invoer voor PUT
	$form['wx_info']['put_request_input'] = array (
		'#type' => 'textfield',
		'#title' => 'input',
		'#size' => 35,
		);
	
	// Submit-knop
	$form['wx_info']['put_request_submit'] = array (
		'#type' => 'submit',
		'#value' => t('PUT'),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function put_request_form_submit($form, $form_state) {
	$handle = background_process_start('start_request', 'PUT', $form_state['values']['put_request_input']);
}

///////////////////////
// POST REQUEST FORM //
///////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function post_request_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('POST Request'),
	);
	
	// Invoer voor POST
	$form['wx_info']['post_request_input'] = array (
		'#type' => 'textfield',
		'#title' => 'input',
		'#size' => 35,
		);
	
	// Submit-knop
	$form['wx_info']['post_request_submit'] = array (
		'#type' => 'submit',
		'#value' => t('POST'),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function post_request_form_submit($form, $form_state) {
	$handle = background_process_start('start_request', 'POST', $form_state['values']['post_request_input']);
}

/////////////////////////
// DELETE REQUEST FORM //
/////////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function delete_request_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('DELETE Request'),
	);
	
	// Submit-knop
	$form['wx_info']['delete_request_submit'] = array (
		'#type' => 'submit',
		'#value' => t('DELETE'),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function delete_request_form_submit($form, $form_state) {
	$handle = background_process_start('start_request', 'DELETE');
}

//////////////
// URI FORM //
//////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function uri_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('URI form'),
	);
	
	// Eventuele fout
	$form['uri']['error'] = array(
		'#type' => 'item',
		'#markup' => variable_get('bad_uri', ''),
	);
	variable_del('bad_uri');
	
	// Invoer textbox voor URI
	$form['uri']['invoer'] = array(
		'#type' => 'textfield',
		'#title' => 'Geef een URI',
		'#default_value' => '',
	);
	
	// Submit-knop
	$form['uri']['submit'] = array (
		'#type' => 'submit',
		'#value' => t('Invoeren'),
	);
		
	$form['#action'] = '';
	
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function uri_form_submit($form, $form_state) {
	global $user;
	
	$pattern = '/([^\/]+)\/(.*)/i';
	if(preg_match($pattern, $form_state['values']['invoer'], $matches)){
		$query = db_select('coap_sensors_resources', 'resources');
		$query
			->fields('resources', array('uri'))
			->condition('uri', $form_state['values']['invoer'], '=');
		$result = $query->execute();
		
		if($result->rowCount() == 0){
			$id = db_insert('coap_sensors_resources')
				->fields(array(
					'uri' => $form_state['values']['invoer'],
					'observable' => 1,
					'last_error' => 'none',
				))
				->execute();
		}
		
		// Watch bij alle rijen van de user op nul zetten
		$num_updated = db_update('coap_sensors_users')
			->fields(array(
				'watch' => 0,
			))
			->condition('uid', $user->uid, '=')
			->execute();
		
		// Watch van net toegevoegde URI op 1 zetten
		$id = db_insert('coap_sensors_users')
			->fields(array(
				'uid' => $user->uid,
				'uri' => $form_state['values']['invoer'],
				'observe' => 0,
				'watch' => 1,
				'responded' => 0,
			))
			->execute();
	}
	else{
		variable_set('bad_uri', 'Er werd een ongeldige URI opgegeven.');
	}
}

//////////////////////
// OBSERVE FORM //
//////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function observe_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('Observe form'),
	);
	
	global $user;
	
	// Checkbox per observable resource
	$query = db_select('coap_sensors_users', 'users');
	$query
		->fields('users', array('uid', 'uri', 'observe'))
		->condition('uid', $user->uid,'=');
	$result = $query->execute();
	foreach ($result as $record){
		$form['observe'][$record->uri] = array(
			'#type' => 'checkbox',
			'#title' => $record->uri,
			'#default_value' => $record->observe,
		);
	}
	
	// Submit-knop
	$form['observe']['temperatuur_udp_url_submit'] = array (
		'#type' => 'submit',
		'#value' => t('Observe'),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function observe_form_submit($form, $form_state) {
	global $user;
	
	$query = db_select('coap_sensors_users', 'users');
	$query
		->fields('users', array('uid', 'uri'))
		->condition('uid', $user->uid, '=');
	$result = $query->execute();
	foreach ($result as $record){
		$observe_query = db_select('coap_sensors_users', 'users');
		$observe_query
			->fields('users', array('uid', 'uri', 'observe'))
			->condition('uri', $record->uri, '=')
			->condition('observe', 1, '=');
		$observe_result = $observe_query->execute();
		$num_observers = $observe_result->rowCount();
	
		if($form_state['values'][$record->uri] != 0 && $num_observers == 0){
			background_process_start('start_observing', $record->uri);
		}
		$num_updated = db_update('coap_sensors_users')
			->fields(array(
				'observe' => $form_state['values'][$record->uri],
			))
			->condition('uri', $record->uri, '=')
			->condition('uid', $user->uid, '=')
			->execute();
			
		$observe_query = db_select('coap_sensors_users', 'users');
		$observe_query
			->fields('users', array('uid', 'uri', 'observe'))
			->condition('uri', $record->uri, '=')
			->condition('observe', 1, '=');
		$observe_result = $observe_query->execute();
		if($observe_result->rowCount() == 0){
			coap_library_stop_observing('coap_sensors', $record->uri);
		}
	}
}


//////////////////////
// PRIVATE FUNCTIES //
//////////////////////

function start_observing($uri){
	$pattern = '/([^\/]+)\/(.*)/i';
	if(preg_match($pattern, $uri, $matches)){
		$ip = $matches[1];
		$resource = $matches[2];
		
		$coap_factory = new CoAPMessageFactory('coap_sensors', $ip, $resource);
		$message = $coap_factory->create_observe_get_request($resource);
		$message->send_message();
	}
}

function coap_sensors_stop_observers($ip, $resource){
	$num_updated = db_update('CoAP_users')
			->fields(array(
				'observe' => 0,
			))
			->condition('uri', $ip . "/" . $resource, '=')
			->execute();
}

function get_number_of_observers($ip, $resource){
	$query = db_select('coap_sensors_users', 'users');
	$query
		->fields('users', array('uri', 'observe'))
		->condition('uri', $ip . "/" . $resource, '=')
		->condition('observe', 1, '=');
	$result = $query->execute();
	return $result->rowCount();
}

function start_request($method, $payload=''){
	global $user;
	$query = db_select('coap_sensors_users', 'users');
	$query
		->fields('users', array('uid', 'uri', 'watch'))
		->condition('watch', 1, '=')
		->condition('uid', $user->uid, '=');
	$result = $query->execute();
	
	foreach($result as $record){
		$pattern = '/([^\/]+)\/(.*)/i';
		if(preg_match($pattern, $record->uri, $matches)){
			$coap_factory = new CoAPMessageFactory('coap_sensors', $matches[1], $matches[2]);
			$coap_message = $coap_factory->create_message_with_header_and_token('CON', $method, 0);
			$coap_message->add_option(11, $matches[2]);
			if($payload != ''){
				$coap_message->add_payload($payload);
			}
			$response_obj = $coap_message->send_message();
			if($response_obj != null){
				$num_updated = db_update('coap_sensors_users')
				->fields(array(
					'responded' => 1,
					'last_method' => $method,
					'last_response' => $response_obj->get_payload(),
					'response_type' => $response_obj->get_message_code(),
				))
				->condition('uid', $user->uid, '=')
				->execute();
			}
			else{
				$num_updated = db_update('coap_sensors_users')
				->fields(array(
					'responded' => 1,
					'last_method' => $method,
					'last_response' => 'no response returned',
				))
				->condition('uid', $user->uid, '=')
				->execute();
			}
		}
	}
}

// Gets the temperature out of a payload (Celsius)
// Return the original payload if temperature could not be parsed
function coap_sensors_get_temperature($payload){
	$pattern = '/value\s+(.*)C/i';
	if(preg_match($pattern, $payload, $matches)){
		$temperature = $matches[1];
		return $temperature;
	}
	else{
		return $payload;
	}
}

function coap_sensors_receive_error($error_message, $ip, $resource){
	// $num_updated = db_update('coap_sensors_resources')
			// ->fields(array(
				// 'last_error' => $error_message,
			// ))
			// ->condition('uri', $ip . "/" . $resource, '=')
			// ->execute();
}

function coap_sensors_receive_response($response_obj){
	// $max_age = $response_obj->get_max_age();
	// $value = $response_obj->get_payload();
	// $format = $response_obj->get_content_format();
	// if($format == 'text/plain'){
		// $value = coap_sensors_get_temperature($value);
	// }
	// variable_set('test', $response_obj->get_ip() . '/' . $response_obj->get_resource());
	
	// global $user;
	// variable_set('test', 'voor eerste insert');
	// $hid = db_insert('coap_values')
		// ->fields(array(
			// 'payload' => $response_obj->get_payload(),
			// 'content_format' => $format,
			// 'original_response' => $response_obj->getHexMessage(),
			// 'parsed_value' => $value,
			// 'max_age' => $max_age,
			// 'uri' => ($response_obj->get_ip() . '/' . $response_obj->get_resource()),
			// 'uid' => $user->uid,
		// ))
		// ->execute();
	// variable_set('test', 'na eerste insert');
	
	// $query = db_select('coap_sensors_users', 'users');
	// $query
		// ->fields('users', array('uri', 'uid', 'observe'))
		// ->condition('uri', $response_obj->get_ip() . '/' . $response_obj->get_resource(), '=')
		// ->condition('observe', 1, '=')
		// ->condition('uid', $user->uid, '!=');
	// $result = $query->execute();
	
	// foreach($result as $record){
		// $hid = db_insert('coap_sensors_values')
			// ->fields(array(
				// 'payload' => $response_obj->get_payload(),
				// 'content_format' => $format,
				// 'original_response' => $response_obj->getHexMessage(),
				// 'parsed_value' => $value,
				// 'max_age' => $max_age,
				// 'uri' => $response_obj->get_ip() . '/' . $response_obj->get_resource(),
				// 'uid' => $record->uid,
			// ))
			// ->execute();
	// }
}