<?php
// $Id$

include_once ('weather_info.inc');

function weather_info_block_info() {
	$blocks['user_custom'] = array(
		'info' => t('Weather block custom for each user'),
		);
	return $blocks;
}

//function weather_info_block_view($delta='') {
//	$block['subject'] = t('Get Weather');
//	$block['content'] = t('Initial content goes here.');
//	return $block;
//}

function weather_location_form($form_in, &$form_state) {
	$form['wx_info_title'] = array (
		'#value' => t('Location'),
		);
	//$form['wx_info']['weather_location'] = array (
//		'#type' => 'textfield',
//		'#size' => 20,
		//'#maxlength' => 20,
		//);
	//$form['wx_info']['weather_location_submit'] = array (
		//'#type' => 'submit',
		//'#value' => t('Search'),
		//);
	//$form['#action'] = '/';
	return $form;
}

//function weather_location_form_validate($form, $form_state) {
//	$location = trim($form_state['values']['weather_location']);
//	$weather = weather_info_get_weather($location, 'en');
//	if (!$weather) {
//		form_set_error('weather_location', t('Location %location not found.',
//			array('%location' => $location)));
//	}
//}
//
//function weather_location_form_submit($form, $form_state) {
//	$location = trim($form_state['values']['weather_location']);
//	variable_set('current_location', $location);
//}

function weather_info_block_view($delta='') {
	$block = null;
	$block_content = null;
	$block_content .= "<p>Geef een WOEID op:</p><input type='text' id='invoer' /><input type='submit' id='zoek' value='Zoek' class='form-submit' ><div id='weerblok' ></div>";
	drupal_add_js(drupal_get_path('module', 'weather_info') .'/js/jquery-1.9.1.min.js');
	drupal_add_js(drupal_get_path('module', 'weather_info') .'/js/jquery.gracefulWebSocket.js');
	drupal_add_js(drupal_get_path('module', 'weather_info') .'/js/weather_info.js');
	//$unit = 'F';
	//$language = 'en';
	//$location = variable_get('current_location', null);
	//if ($location) {
	//	$weather = weather_info_get_weather($location, $language);
	//	if ($weather) {
	//		$current = $weather->channel;
	//		$block_content .= '<div class="currentConditions">';
	//		$block_content .= $current->description;
	//		$block_content .= $current->item->description;
	//		$block_content .= '</div>';
	//		$block_content .= '<div class="history"><table>';
	//		
	//		$query = db_select('weather_info', 'weather');
	//		$query
	//			->fields('weather', array('hid', 'weather_xml'))
	//			->range(0,5);
	//		$result = $query->execute();
	//		foreach ($result as $record){
	//			$block_content .= '<tr><td>' . $record->hid . '</td><td>' . $record->weather_xml . '</td></tr>';
	//		}
	//		
	//		$block_content .= '</table></div>';
	//		$block['subject'] = $weather->title;
	//	}
	//	else {
	//		form_set_error('weather_location',
	//			t('Location @loc not found.', array('@loc' => $location)));
	//		variable_set('current_location', null);
	//		$block['subject'] = t('Get Weather');
	//	}
	//}
	$temp = drupal_get_form('weather_location_form');
	$block_content .= drupal_render($temp);
	$block['content'] = $block_content;
	return $block;
}