<?php

/**
 * @file
 * Module for the Coap_resource_value Entity - a starting point to create your own Entity
 * and associated administration interface
 */  


/**
 * Implement hook_entity_info().
 *
 * We define two entities here - the actual entity that will hold our domain
 * specific information and an entity that holds information about the different
 * types of entities. See here: http://drupal.org/node/977380 for a discussion on this
 * choice.
 */
function coap_resource_value_entity_info() {
  $return['coap_resource_value'] = array(
    'label' => t('Coap_resource_value'),
    // The entity class and controller class extend the classes provided by the
    // Entity API
    'entity class' => 'Coap_resource_value',
    'controller class' => 'Coap_resource_valueController',
    'base table' => 'coap_resource_value',
    'fieldable' => TRUE,
    'entity keys' => array(
        'id' => 'coap_resource_value_id',
        'bundle' => 'type',
    ),
    // Bundles are defined by the coap_resource_value types below
    'bundles' => array(),
    // Bundle keys tell the FieldAPI how to extract information from the bundle objects
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'creation callback' => 'coap_resource_value_create',
    'access callback' => 'coap_resource_value_access',
    'module' => 'coap_resource_value',
    // The information below is used by the Coap_resource_valueUIController (which extends the EntityDefaultUIController)
    'admin ui' => array(
      'path' => 'admin/content/coap_resource_values',
      'file' => 'coap_resource_value.admin.inc',
      'controller class' => 'Coap_resource_valueUIController',
      'menu wildcard' => '%coap_resource_value',
    ),
  );
  // The entity that holds information about the entity types	  
  $return['coap_resource_value_type'] = array(
    'label' => t('Coap_resource_value Type'),
    'entity class' => 'Coap_resource_valueType',
    'controller class' => 'Coap_resource_valueTypeController',
    'base table' => 'coap_resource_value_type',
    'fieldable' => FALSE,
    'bundle of' => 'coap_resource_value',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'coap_resource_value_type_access',
    'module' => 'coap_resource_value',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/coap_resource_value_types',
      'file' => 'coap_resource_value_type.admin.inc',
      'controller class' => 'Coap_resource_valueTypeUIController',
    ),
  );

  return $return;
}


/**
 * Implements hook_entity_info_alter().
 *
 * We are adding the info about the coap_resource_value types via a hook to avoid a recursion
 * issue as loading the coap_resource_value types requires the entity info as well.
 *
 * @todo This needs to be improved
 */
function coap_resource_value_entity_info_alter(&$entity_info) {
  foreach (coap_resource_value_get_types() as $type => $info) {
    $entity_info['coap_resource_value']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/coap_resource_value_types/manage/%coap_resource_value_type',
        'real path' => 'admin/structure/coap_resource_value_types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer coap_resource_value types'),
      ),
    );
  }
}
  

/**
 * Implements hook_permission().
 */
function coap_resource_value_permission() {
  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity
  $permissions = array(
    'administer coap_resource_value types' => array(
      'title' => t('Administer coap_resource_value types'),
      'description' => t('Create and delete fields for coap_resource_value types, and set their permissions.'),
    ),
    'administer coap_resource_values' => array(
      'title' => t('Administer coap_resource_values'),
      'description' => t('Edit and delete all coap_resource_values'),
    ),  
  );
  
  //Generate permissions per coap_resource_value 
  foreach (coap_resource_value_get_types() as $type) {
    $type_name = check_plain($type->type);
    $permissions += array(
      "edit any $type_name coap_resource_value" => array(
        'title' => t('%type_name: Edit any coap_resource_value', array('%type_name' => $type->label)),
      ),
      "view any $type_name coap_resource_value" => array(
        'title' => t('%type_name: View any coap_resource_value', array('%type_name' => $type->label)),
      ),
    );
  }
  return $permissions;  
}


/**
 * Determines whether the given user has access to a coap_resource_value.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $coap_resource_value
 *   Optionally a coap_resource_value or a coap_resource_value type to check access for. If nothing is
 *   given, access for all coap_resource_values is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function coap_resource_value_access($op, $coap_resource_value = NULL, $account = NULL) {
  if (user_access('administer coap_resource_values', $account)) {
    return TRUE;
  }
  if (isset($coap_resource_value) && $type_name = $coap_resource_value->type) {
    $op = ($op == 'view') ? 'view' : 'edit';
    if (user_access("$op any $type_name coap_resource_value", $account)) {
      return TRUE;
    }
  }
  return FALSE;
}


/**
 * Access callback for the entity API.
 */
function coap_resource_value_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer coap_resource_value types', $account);
}


/**
 * Gets an array of all coap_resource_value types, keyed by the type name.
 *
 * @param $type_name
 *   If set, the type with the given name is returned.
 * @return Coap_resource_valueType[]
 *   Depending whether $type isset, an array of coap_resource_value types or a single one.
 */
function coap_resource_value_get_types($type_name = NULL) {
  // entity_load will get the Entity controller for our coap_resource_value entity and call the load
  // function of that object - we are loading entities by name here.
  $types = entity_load_multiple_by_name('coap_resource_value_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}


/**
 * Menu argument loader; Load a coap_resource_value type by string.
 *
 * @param $type
 *   The machine-readable name of a coap_resource_value type to load.
 * @return
 *   A coap_resource_value type array or FALSE if $type does not exist.
 */
function coap_resource_value_type_load($type) {
  return coap_resource_value_get_types($type);
}


/**
 * Fetch a coap_resource_value object. Make sure that the wildcard you choose 
 * in the coap_resource_value entity definition fits the function name here.
 *
 * @param $coap_resource_value_id
 *   Integer specifying the coap_resource_value id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $coap_resource_value object or FALSE if it cannot be loaded.
 *
 * @see coap_resource_value_load_multiple()
 */
function coap_resource_value_load($coap_resource_value_id, $reset = FALSE) {
  $coap_resource_values = coap_resource_value_load_multiple(array($coap_resource_value_id), array(), $reset);
  return reset($coap_resource_values);
}


/**
 * Load multiple coap_resource_values based on certain conditions.
 *
 * @param $coap_resource_value_ids
 *   An array of coap_resource_value IDs.
 * @param $conditions
 *   An array of conditions to match against the {coap_resource_value} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of coap_resource_value objects, indexed by coap_resource_value_id.
 *
 * @see entity_load()
 * @see coap_resource_value_load()
 */
function coap_resource_value_load_multiple($coap_resource_value_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('coap_resource_value', $coap_resource_value_ids, $conditions, $reset);
}


/**
 * Deletes a coap_resource_value.
 */
function coap_resource_value_delete(Coap_resource_value $coap_resource_value) {
  $coap_resource_value->delete();
}


/**
 * Delete multiple coap_resource_values.
 *
 * @param $coap_resource_value_ids
 *   An array of coap_resource_value IDs.
 */
function coap_resource_value_delete_multiple(array $coap_resource_value_ids) {
  entity_get_controller('coap_resource_value')->delete($coap_resource_value_ids);
}


/**
 * Create a coap_resource_value object.
 */
function coap_resource_value_create($values = array()) {
  return entity_get_controller('coap_resource_value')->create($values);
}


/**
 * Saves a coap_resource_value to the database.
 *
 * @param $coap_resource_value
 *   The coap_resource_value object.
 */
function coap_resource_value_save(Coap_resource_value $coap_resource_value) {
  return $coap_resource_value->save();
}


/**
 * Saves a coap_resource_value type to the db.
 */
function coap_resource_value_type_save(Coap_resource_valueType $type) {
  $type->save();
}


/**
 * Deletes a coap_resource_value type from the db.
 */
function coap_resource_value_type_delete(Coap_resource_valueType $type) {
  $type->delete();
}


/**
 * URI callback for coap_resource_values
 */
function coap_resource_value_uri(Coap_resource_value $coap_resource_value){
  return array(
    'path' => 'coap_resource_value/' . $coap_resource_value->coap_resource_value_id,
  );
}


/**
 * Menu title callback for showing individual entities
 */
function coap_resource_value_page_title(Coap_resource_value $coap_resource_value){
  return $coap_resource_value->payload;
}


/**
 * Sets up content to show an individual coap_resource_value
 * @todo - get rid of drupal_set_title();
 */
function coap_resource_value_page_view($coap_resource_value, $view_mode = 'full') {    
  $controller = entity_get_controller('coap_resource_value');  
  $content = $controller->view(array($coap_resource_value->coap_resource_value_id => $coap_resource_value));
  drupal_set_title($coap_resource_value->payload);
  return $content;
}


/**
 * Implements hook_views_api().
 */
function coap_resource_value_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'coap_resource_value') . '/views',
  );
}


/**
 * Implement hook_theme().
 */
function coap_resource_value_theme() {
  return array(
    'coap_resource_value_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'coap_resource_value.admin.inc',
    ),
    'coap_resource_value' => array(
      'render element' => 'elements',
      'template' => 'coap_resource_value',
    ),
   'coap_resource_value_sample_data' => array(
      'variables' => array('coap_resource_value_sample_data', 'coap_resource_value' => NULL),
      'template' => 'coap_resource_value-sample-data',
    ),


  );
}  


/**
 * Implements hook_menu_local_tasks_alter().
 */
function coap_resource_value_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/structure/coap_resource_values/add' on 'admin/structure/coap_resource_values'.
  if ($root_path == 'admin/content/coap_resource_values') {
    $item = menu_get_item('admin/content/coap_resource_values/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}


/**
 * The class used for coap_resource_value entities
 */
class Coap_resource_value extends Entity {
  
  public function __construct($values = array()) {
    parent::__construct($values, 'coap_resource_value');
  }

  protected function defaultLabel() {
    return $this->payload;
  }

  protected function defaultUri() {
    return array('path' => 'coap_resource_value/' . $this->coap_resource_value_id);
  }
  
  
}


/**
 * The class used for coap_resource_value type entities
 */
class Coap_resource_valueType extends Entity {
  
  public $type;
  public $label;
  
  public function __construct($values = array()) {
    parent::__construct($values, 'coap_resource_value_type');
  }
  
}


/**
 * The Controller for Coap_resource_value entities
 */
class Coap_resource_valueController extends EntityAPIController {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }


  /**
   * Create a coap_resource_value - we first set up the values that are specific
   * to our coap_resource_value schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the coap_resource_value.
   *
   * @return
   *   A coap_resource_value object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our Coap_resource_value
    $values += array( 
      'coap_resource_value_id' => '',
      'is_new' => TRUE,
      'title' => '',
	  'uid' => '',
      'created' => '',
      'changed' => '',
      'data' => '',
	  'content_format' => '',
	  'payload' => '',
	  'parsed_value' => '',
	  'max_age' => '',
	  'original_response' => '',
    );
    
    $coap_resource_value = parent::create($values);
    return $coap_resource_value;
  }
  
  /**
   * Overriding the buldContent function to add entity specific fields
   */
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $content = parent::buildContent($entity, $view_mode, $langcode, $content);
    $content['coap_resource_value_sample_data'] =  array(
      '#markup' => theme('coap_resource_value_sample_data', array('coap_resource_value_sample_data' => check_plain($entity->data['sample_data']), 'coap_resource_value' => $entity)),
    );

    return $content;
  }
  
}


/**
 * The Controller for Coap_resource_value entities
 */
class Coap_resource_valueTypeController extends EntityAPIControllerExportable {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }
  
   /**
   * Create a coap_resource_value type - we first set up the values that are specific
   * to our coap_resource_value type schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the coap_resource_value.
   *
   * @return
   *   A coap_resource_value type object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our Coap_resource_value
    $values += array( 
      'id' => '',
      'is_new' => TRUE,
      'data' => '',
    );
    $coap_resource_value_type = parent::create($values);
    return $coap_resource_value_type;
  }

}