<?php
/**
* Implements hook_elements().
*/
function custom_field2_element_info() {
  return array(
    'myelement' => array(
      '#input' => TRUE,
      '#tree' => TRUE,
      '#process' => array('custom_field2_element_process_callback'),
      '#element_validate' => array('custom_field2_element_validate'),
      '#theme' => array('custom_field2_element'),
      '#theme_wrappers' => array('form_element'),
    ),
  );
}

/**
* Generates form elements for my element.
*/
function custom_field2_element_process_callback($element, &$form_state) {
  // Add two textfields to the element
  $element['textfield1'] = array(
    '#type' => 'textfield',
    '#title' => t('Textfield 1'),
  );
  $element['textfield2'] = array(
    '#type' => 'textfield',
    '#title' => t('Textfield 2'),
  );
  
  return $element;
}