<?php
 
function custom_ct_node_info() {
  return array(
      'custom_ct' => array(
          'name' => t('custom_content_type'),
          'base' => 'custom_ct',
          'description' => t('A custom content type.'),
          'has_title' => TRUE,
          'title_label' => t('custom_ct Title'),
          'locked' => FALSE,
		  
		  
		  
      /**
       *  Submission form settings (core functional)
       *  ------------------------------------------
       *
       *  Preview before submitting
       *    node_preview_{$type}
       *    value <int>:
       *      0 => Disabled
       *      1 => Optional
       *      2 => Required
       */
      'node-preview' => 0,

      /**
       *  Publishing options (core functional)
       *  ------------------------------------
       *
       *  Default options
       *    node_options_{$type}
       *    value <array>:
       *      array('status', 'promote', 'sticky', 'revision')
       */
      'node-options' => array('status'),

      /**
       *  Display settings
       *  ----------------
       *
       *  Display author and date information
       *    node_submitted_{$type}
       *    value <int>:
       *      0 => Hide author and date information
       *      1 => Display author and date information
       */
      'node-submitted' => 0,

      /**
       *  Comment settings
       *  ----------------
       */
      'comment' => array(
        /**
         *  Default comment setting for new content
         *    comment_{$type}
         *    values <int>:
         *      0 => hidden
         *      1 => closed
         *      2 => open
         */
        'status' => 0,
		
        /**
         *  Threading
         *    comment_default_mode_{$type}
         *    values <int>:
         *      0 => don't show
         *      1 => show
         */
        //'default-mode' => 1,

        /**
         *  Allow anonimous to leave commentns
         *       comment_anonymous_{$type}
         *    values <int>:
         *      0 => forbid
         *      1 => allow
         */
        //'anonymous' => 0,

        /**
         *  Comments per page
         *    comment_default_per_page_{$type}
         *    values <int>:
         *      10, 30, 50, 70, 90, 150, 200, 250, 300
         */
        //'default-per-page' => 50,

        /**
         *  Show reply form on the same page as comments
         *    comment_form_location_{$type}
         *    values:
         *      0 => hide
         *      1 => show
         */
        //'form-location' => 0,

        /**
         *  Preview comment
         *    comment_preview_{$type}
         *    values <int>:
         *      0 => disabled
         *      1 => optional
         *      2 => required
         */
        //'preview' => 0,

        /**
         *  Allow comment title
         *    comment_subject_field_{$type}
         *    values <int>:
         *      0 => disallow
         *      1 => allow
         */
        //'subject-field' => 0,
      ),
		  
		  
		  
      ),
  );
}
 
function custom_ct_form($node, $form_state) {
  $type = node_type_get_type($node);
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#default_value' => !empty($node->title) ? $node->title : '',
    '#required' => TRUE, '#weight' => -5
  );
 
  return $form;
}