<?php

require_once(drupal_get_path('module', 'coap_library') . '/coap_library_classes.inc');
require_once(drupal_get_path('module', 'coap_resource') . '/includes/coap_discovery.inc');

/**
 * Implementation of hook_help().
 */
function coap_resource_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      return t('De coap_resource module stelt de gebruiker in staat een sensornetwerk gebruiksvriendelijk en dynamisch te beheren.');
    case 'admin/help#coap_resource':
      return t('<h3>Description:</h3><p>De coap_resource module stelt de gebruiker in staat een sensornetwerk gebruiksvriendelijk en dynamisch te beheren.</p>');
  }
}

/**
 * Implements hook_menu().
 * Creëert het pad waarnaar jQuery een ajax call kan uitvoeren en de callback-functie
 */
function coap_resource_menu() {
	$items = array();
	$items['admin/config/content/coap_resource'] = array(
		'title' => 'CoAP resource settings',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('coap_resource_admin_settings'),
		'access callback' => TRUE,
		'description' => 'Global configuration of the CoAP resource module functionality.',
		'type' => MENU_NORMAL_ITEM,
	);
	$items["coap_resource/poll"] = array(
		"title" => "Get last entry",
		"page callback" => "coap_resource_page_callback",
		"access callback" => true,
		"type" => MENU_CALLBACK
	);
	$items["coap_resource/discovery/%"] = array(
		"title" => "Discovery",
		"page callback" => "coap_discovery_page_callback",
		"page arguments" => array(2),
		"access callback" => true,
		"type" => MENU_CALLBACK
	);
	$items["coap_resource/interval/%"] = array(
		"title" => "Change polling interval",
		"page callback" => "temperatuur_met_coap_library_change_interval",
		"page arguments" => array(2),
		"access callback" => true,
		"type" => MENU_CALLBACK
	);
	$items["coap_resource/request/%"] = array(
		"title" => "Start GET request for given URI",
		"page callback" => "coap_resource_start_request_for_uri",
		"page arguments" => array(2, 3, 4),
		"access callback" => true,
		"type" => MENU_CALLBACK
	);
	$items["coap_resource/observe/%"] = array(
		"title" => "Starts observing the given URI",
		"page callback" => "coap_resource_handle_observing_for_uri",
		"page arguments" => array(2, 3),
		"access callback" => true,
		"type" => MENU_CALLBACK
	);
	
	$items['node/%coap_resource_menu/view/discovery'] = array(
		'title' => 'Discovery',    
		'access callback' => TRUE,
		'weight' => 2,
		'type' => MENU_DEFAULT_LOCAL_TASK,
	);
	
	$items['node/%coap_resource_menu/view/resources'] = array(
		'title' => 'Resources',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('coap_resource_form', 1),
		'access callback' => TRUE,
		'weight' => 4,
		'type' => MENU_LOCAL_TASK,
	);
	
	$items['node/%coap_resource_menu/view/configuration'] = array(
		'title' => 'Configuration',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('coap_resource_admin_settings'),
		'access callback' => TRUE,
		'weight' => 8,
		'type' => MENU_LOCAL_TASK,
	);

  return $items;
}

// function coap_resource_form_alter(&$form, &$form_state, $form_id){
	// dpm($form);
// }

function coap_resource_admin_settings() {
	$form['message_container'] = array
	(
		'#type' => 'container',
		'#prefix' => "De configuratietab van de module coap_resources.",
	);
	$form = system_settings_form($form);
	return $form;
}

/**
 * Menu loader callback. Load a coap_resource node.
 */
function coap_resource_menu_load($nid) {
	if (!is_numeric($nid)) {
		return FALSE;
	}
	$node = node_load($nid);
	if (!isset($node->type) || ($node->type != 'coap_general' && $node->type != 'coap_device')) {
		return FALSE;
	}
	return $node;
}

//////////
// FORM //
//////////

//Act on a node that is being assembled before rendering.
function coap_resource_node_view($node, $view_mode, $langcode) {
	if($node->type == 'coap_general'){
		$node->content['coap_discovery_form'] = drupal_get_form('coap_discovery_form', $node);
	}
	else if($node->type == 'coap_resource'){
		$node->content['coap_resource_form'] = drupal_get_form('coap_resource_form', $node);
	}
	else if($node->type == 'coap_device'){
		$node->content['coap_discovery_form'] = drupal_get_form('coap_discovery_form', $node);
	}
	return $node;
}

function create_my_node(){
	global $user;
	// Create an Entity
	$new_node = entity_create('node', array('type' => 'test_content_type'));
	// Specify the author
	$new_node->uid = $user->uid;
	// Create a Entity Wrapper of that new Entity
	$entity = entity_metadata_wrapper('node',$new_node);
	 
	// Specify the title
	$entity->title = 'Test node';
	dpm($entity->getPropertyInfo());
	// Add field data... SO MUCH BETTER!
	dpm($entity->field_textarea);
	//$entity->coap_resource_uri_field->set('2001:6a8:1d80:200::2/obs');
	$entity->field_textarea->set('2001:6a8:1d80:200::2/obs');
	//$entity->field_reference->set('2001:6a8:1d80:200::2/obs');
	// Save the node.
	// $entity->save();
}

function coap_resource_form($form, &$form_state, $node) {
	drupal_add_js('https://www.google.com/jsapi'); // JavaScript bestand toevoegen
	drupal_add_js(drupal_get_path('module', 'coap_resource') . '/js/coap_resource.js'); // JavaScript bestand toevoegen	
	global $user;
	create_my_node();
	
	$nid = $node->nid;
	$form['nid'] = array
	(
		'#type' => 'hidden',
		'#value' => $node->nid,
	);	
	
	$current_interval = 1;
	$empty = TRUE;
	
	$query = db_select('coap_resource_users', 'users');
	$query->join('coap_resource_resources', 'resources', 'users.uri = resources.uri');
	$query
		->fields('users')
		->fields('resources')
		->condition('uid', $user->uid, '=')
		->condition('device',0,'=')
		->condition('nid',$nid,'=')
		->condition('watch', 1, '=');
	$resources = $query->execute();
	
	$first_resource  = $resources->fetchAssoc();
	//dpm($first_resource);
	if(isset($first_resource)){
		// dpm($first_resource);
		$empty =0;
		$current_interval = $first_resource['polling_interval'];
		$uri = $first_resource['uri'];
	}
	// foreach($resources as $record){
		// dpm($record);
	// }
	// foreach ($resources as $record){
		// $empty = 0;
		// $current_interval = $record->polling_interval;
		// $uri = $record->uri;
	// }		
	
	if($node->type == 'coap_general')
		coap_resource_uri_form($form, $form_state);
		
	if(!$empty && $empty != 1){
		$form['polling_container'] = array(
			'#type' => 'container',
			'#prefix' => "Polling gebeurt om de <input id='polling_invoer' type='text' size='1' value='" . $current_interval . "' > seconden. <button id='polling_button' type='button' >Wijzigen</button></br>",
		);
		
		// $form['polling_button'] = array(
			// '#type' => 'submit',
			// '#value' => 'Wijzigen',
			// '#prefix' => "Polling gebeurt om de <input id='polling_invoer' type='text' size='1' value='" . $current_interval . "' > seconden.",
			// '#id' => 'polling_button',
			// '#submit' => 'do_nothing',
		// );
		
		if($node->type != 'coap_resource'){
			coap_resource_observe_form($form, $form_state, $nid);
			coap_resource_bekijken_form($form, $form_state, $nid);
		}
		else{
			//dpm($first_resource);
			if(isset($first_resource['obs'])){
				// dpm($first_resource['uri']);
				$form['observe'][$first_resource['uri']] = array(
					'#type' => 'hidden',
				);
				$form['observe_button'] = array(
					'#type' => 'submit',
					'#submit' => array('coap_resource_observe_form_submit'),
				);
				if(!$first_resource['observe']){
					$form['observe'][$first_resource['uri']]['#value'] = 1;
					$form['observe_button']['#default_value'] = 'Start observing';
				}
				else{
					$form['observe'][$first_resource['uri']]['#value'] = 0;
					$form['observe_button']['#default_value'] = 'Stop observing';
				}
			}
		}
		coap_resource_get_request_form($form, $form_state);
		coap_resource_put_request_form($form, $form_state);
		coap_resource_post_request_form($form, $form_state);
		coap_resource_delete_request_form($form, $form_state);
		
		// dpm($uri);
		// dpm($first_resource['uri']);
		
		// Tabel met geschiedenis van opvragingen(5 laatste)
		$result = db_select('coap_resource_values', 'coap_values')
			->fields('coap_values', array('hid', 'parsed_value', 'max_age', 'timestamp', 'uri', 'uid'))
			->condition('uri', $uri, '=')
			->condition('uid', $user->uid, '=')
			->orderBy('hid', 'DESC')
			->range(0,5)
			->execute();
		
		$prefix = "<tr><td colspan = '4' ><label id = 'response' >Response: </label></td><tr><td colspan = '4' ><label id = 'response_type' >Response type: </label></td></tr></table>";
		$prefix .= "<img style = 'visibility:hidden;' src = '' id = 'errorimg' /><label id='error' ></label>"; // elementen om fouten te tonen
		$prefix .= "<table id='historytable' ><tr><th>Hid</th><th>Value</th><th>Max age</th><th>Timestamp</th></tr>";
		$nr = 1;
		foreach ($result as $record){ // voegt telkens een rij toe aan de tabel, waarbij de elementen een id met een rij-nr erna krijgen
			$value = $record->parsed_value;
			$hid = $record->hid;
			$max_age = $record->max_age;
			$timestamp = $record->timestamp;
			$prefix .= "<tr><td id='hid" . $nr . "' >" . $hid . "</td><td id='temperatuur" . $nr . "' >" . $value . "</td><td id='max_age" . $nr . "' >" . $max_age . "</td><td id='timestamp" . $nr . "' >" . $timestamp . "</td></tr>";
			$nr++;
		}
		while($nr <= 5){ // voegt telkens een rij toe aan de tabel, waarbij de elementen een id met een rij-nr erna krijgen
			$prefix .= "<tr><td id='hid" . $nr . "' >/</td><td id='temperatuur" . $nr . "' > </td><td id='max_age" . $nr . "' > </td><td id='timestamp" . $nr . "' > </td></tr>";
			$nr++;
		}
		$prefix .= "</table>";
		
		$prefix .= "<div id = 'grafiek' ></div>"; // Grafiek
		
		$form['values_container'] = array(
			'#type' => 'container',
			'#prefix' => $prefix,
			'#attributes' => array(
				'class' => array('class-name'),
			),
		);
	}	
	//dpm($node);
	return $form;
}

///////////
// BLOCK //
///////////

/**
 * Implements hook_block_info().
 * Geeft informatie over de block die de module aanbiedt
 */
function coap_resource_block_info() {
	$blocks['user_custom'] = array(
		'info' => t('Blok met mogelijkheid tot opvragen temperatuur en observeren van verloop van temperatuur'),
	);
	return $blocks;
}

/**
 * Implements hook_block_info().
 * Definieert de titel en inhoud van de block
 */
function coap_resource_block_view($delta='') {
	global $user;
	
	$block = null;
	$block['subject'] = 'Temperatuursensoren bevragen met het CoAP protocol';
	$block_content = null;
	
	$current_interval = 1;
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uid', 'polling_interval'))
		->condition('uid', $user->uid, '=');
	$result = $query->execute();
	foreach ($result as $record){
		$current_interval = $record->polling_interval;
	}
	$block_content .= "Polling gebeurt om de <input id = 'polling_invoer' type = 'text' size = '1' value = '" . $current_interval . "' > seconden. <button id = 'polling_button' type = 'button' >Wijzigen</button>";
	
	// URI form
	$temp = drupal_get_form('coap_resource_uri_form');
	$block_content .= drupal_render($temp);
	
	// Observe form
	if($user->uid){
		$temp = drupal_get_form('coap_resource_observe_form');
		$block_content .= drupal_render($temp);
	}
	else{
		$block_content .= '<label>Wegens beschermingsredenen is de observe functionaliteit uitgeschakeld voor anonieme gebruikers. Log in indien u een sensor wenst te observen.</label>';
	}
	
	// Bekijken form
	$temp = drupal_get_form('coap_resource_bekijken_form');
	$block_content .= drupal_render($temp);
	
	// Table offering REST functionality
	$block_content .= "<table id = 'requests' ><th colspan = '4' >Request methods</th><tr><td>";
	
	// GET form
	$temp = drupal_get_form('coap_resource_get_request_form');
	$block_content .= drupal_render($temp) . "</td><td>";
	
	// PUT form
	$temp = drupal_get_form('coap_resource_put_request_form');
	$block_content .= drupal_render($temp) . "</td><td>";
	
	// POST form
	$temp = drupal_get_form('coap_resource_post_request_form');
	$block_content .= drupal_render($temp) . "</td><td>";
	
	// DELETE form
	$temp = drupal_get_form('coap_resource_delete_request_form');
	$block_content .= drupal_render($temp) . "</td></tr>";
	
	$block_content .= "<tr><td colspan = '4' ><label id = 'response' >Response: </label></td><tr><td colspan = '4' ><label id = 'response_type' >Response type: </label></td></tr></table>";
	
	
	$block_content .= "<img style = 'visibility:hidden;' src = '' id = 'errorimg' /><label id='error' ></label>"; // elementen om fouten te tonen
	
	// Te bekijken URI ophalen
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uid', 'uri', 'watch'))
		->condition('uid', $user->uid, '=')
		->condition('watch', 1, '=');
	$result = $query->execute();
	$empty = TRUE;
	foreach($result as $record){
		$empty = FALSE;
		$uri = $record->uri;
	}
	
	if(!$empty){
		// Tabel met geschiedenis van opvragingen(5 laatste)
		$query = db_select('coap_resource_values', 'coap_values');
		$query
			->fields('coap_values', array('hid', 'parsed_value', 'max_age', 'timestamp', 'uri', 'uid'))
			->condition('uri', $uri, '=')
			->condition('uid', $user->uid, '=')
			->orderBy('hid', 'DESC')
			->range(0,5);
		$result = $query->execute();
		$block_content .= "<table id='historytable' ><tr><th>Hid</th><th>Value</th><th>Max age</th><th>Timestamp</th></tr>";
		$nr = 1;
		foreach ($result as $record){ // voegt telkens een rij toe aan de tabel, waarbij de elementen een id met een rij-nr erna krijgen
			$value = $record->parsed_value;
			$hid = $record->hid;
			$max_age = $record->max_age;
			$timestamp = $record->timestamp;
			$block_content .= "<tr><td id='hid" . $nr . "' >" . $hid . "</td><td id='temperatuur" . $nr . "' >" . $value . "</td><td id='max_age" . $nr . "' >" . $max_age . "</td><td id='timestamp" . $nr . "' >" . $timestamp . "</td></tr>";
			$nr++;
		}
		while($nr <= 5){ // voegt telkens een rij toe aan de tabel, waarbij de elementen een id met een rij-nr erna krijgen
			$block_content .= "<tr><td id='hid" . $nr . "' >/</td><td id='temperatuur" . $nr . "' > </td><td id='max_age" . $nr . "' > </td><td id='timestamp" . $nr . "' > </td></tr>";
			$nr++;
		}
		$block_content .= "</table>";
		
		$block_content .= "<div id = 'grafiek' ></div>"; // Grafiek
	}
	
	$block['content'] = $block_content;
	// drupal_add_js('https://www.google.com/jsapi'); // JavaScript bestand toevoegen
	// drupal_add_js(drupal_get_path('module', 'coap_resource') . '/js/coap_resource.js'); // JavaScript bestand toevoegen
	return $block;
}

//////////////
// URI FORM //
//////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function coap_resource_uri_form(&$form, &$form_state) {
	// Eventuele fout
	$form['uri']['error'] = array(
		'#type' => 'item',
		'#markup' => variable_get('bad_uri', ''),
	);
	variable_del('bad_uri');

	// Invoer textbox voor URI
	$form['uri']['invoer'] = array(
		'#type' => 'textfield',
		'#title' => 'Geef een URI',
		'#default_value' => '',	
	);
	
	// Submit-knop
	$form['uri']['submit'] = array (
		'#type' => 'submit',
		'#value' => t('Invoeren'),
		'#submit' => array('coap_resource_uri_form_submit'),
	);
		
	//dpm($form);
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function coap_resource_uri_form_submit($form, $form_state) {
	global $user;
	$nid = $form_state['values']['nid'];
	$pattern = '/([^\/]+)\/(.*)/i';
	if(preg_match($pattern, $form_state['values']['invoer'], $matches)){
		$query = db_select('coap_resource_resources', 'resources');
		$query
			->fields('resources', array('uri'))
			->condition('uri', $form_state['values']['invoer'], '=');
		$result = $query->execute();
		
		if($result->rowCount() == 0){
			$id = db_insert('coap_resource_resources')
				->fields(array(
					'uri' => $form_state['values']['invoer'],
					'last_error' => 'none',
				))
				->execute();
		}
		
		// Watch bij alle rijen van de user op nul zetten
		$num_updated = db_update('coap_resource_users')
			->fields(array(
				'watch' => 0,
			))
			->condition('uid', $user->uid, '=')
			->condition('nid',$nid,'=')
			->execute();
		
		// Watch van net toegevoegde URI op 1 zetten
		$id = db_insert('coap_resource_users')
			->fields(array(
				'uid' => $user->uid,
				'uri' => $form_state['values']['invoer'],
				'observe' => 0,
				'watch' => 1,
				'responded' => 0,
			))
			->execute();
	}
	else{
		variable_set('bad_uri', 'Er werd een ongeldige URI opgegeven.');
	}
}

//////////////////////
//   OBSERVE FORM 	//
//////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function coap_resource_observe_form(&$form, &$form_state, $nid) {
	global $user;
	$form['title'] = array (
		'#value' => t('Observe Form'),
	);
	
	//indien alleen de observables een checkbox mogen krijgen:
	// $query = db_select('coap_resource_users', 'users');
	// $query->join('coap_resource_resources', 'resources', 'users.uri = resources.uri');
	// $query
		// ->fields('users', array('uid', 'uri', 'device', 'observe'))
		// ->fields('resources', array('obs'))
		// ->condition('uid', $user->uid, '=')
		// ->condition('device',0,'=')
		// ->condition('nid',$nid,'=');
	// $resources = $query->execute();

	// foreach ($resources as $record){
		// if($record->obs == 1){
			// $form['observe'][$record->uri] = array(
				// '#type' => 'checkbox',
				// '#title' => $record->uri,
				// '#default_value' => $record->observe,
			// );
		// }
	// }

	// Checkbox per observable resource
	$result = db_select('coap_resource_users', 'users')
		->fields('users', array('uid', 'uri', 'device', 'observe'))
		->condition('uid', $user->uid,'=')
		->condition('device', 0,'=')
		->condition('nid', $nid,'=')
		->execute();
	foreach ($result as $record){
		$form['observe'][$record->uri] = array(
			'#type' => 'checkbox',
			'#title' => $record->uri,
			'#default_value' => $record->observe,
		);
	}
	
	// Submit-knop
	$form['observe']['submit'] = array (
		'#type' => 'submit',
		'#submit' => array('coap_resource_observe_form_submit'),
		'#value' => t('Observe'),
	);
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function coap_resource_observe_form_submit($form, $form_state) {
	global $user;
	
	//	Get URI's for this user and for this node
	$result = db_select('coap_resource_users', 'users')
		->fields('users', array('uid', 'uri'))
		->condition('uid', $user->uid, '=')
		->condition('device', 0, '=')
		->condition('nid', $form_state['values']['nid'], '=')
		->execute();
	foreach ($result as $record){
		//	Get number of observers for the current URI
		$observe_result = db_select('coap_resource_users', 'users')
			->fields('users', array('uid', 'uri', 'observe'))
			->condition('uri', $record->uri, '=')
			->condition('device', 0, '=')
			->condition('observe', 1, '=')
			->execute();
		$num_observers = $observe_result->rowCount();
		
		//	Start observing the current URI if this user is interested and no one else was already observing
		if($form_state['values'][$record->uri] != 0 && $num_observers == 0){
			background_process_start('coap_resource_start_observing', $record->uri);
		}
		
		//	Store in database that this user is observing or not observing the current URI
		$num_updated = db_update('coap_resource_users')
			->fields(array(
				'observe' => $form_state['values'][$record->uri],
			))
			->condition('uri', $record->uri, '=')
			->condition('uid', $user->uid, '=')
			->condition('device', 0, '=')
			->condition('nid', $form_state['values']['nid'], '=')
			->execute();
		
		//	Get number of users that is still observing the current URI
		$observe_result = db_select('coap_resource_users', 'users')
			->fields('users', array('uid', 'uri', 'observe'))
			->condition('uri', $record->uri, '=')
			->condition('device', 0, '=')
			->condition('observe', 1, '=')
			->execute();
		
		//	Stop observing the URI if no one is interested anymore
		if($observe_result->rowCount() == 0){
			coap_library_stop_observing('coap_resource', $record->uri);
		}
	}
}

///////////////////
// BEKIJKEN FORM //
///////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function coap_resource_bekijken_form(&$form, &$form_state, $nid) {
	global $user;
	$result = db_select('coap_resource_users', 'users')
		->fields('users', array('uid', 'uri', 'device', 'watch'))
		->condition('uid', $user->uid,'=')
		->condition('device', 0,'=')
		->condition('nid', $nid,'=')
	->execute();
	
	// Radio buttons om URI te selecteren
	if($result->rowCount() > 0){
		$options = array();
		foreach ($result as $record){
			$options[$record->uri] = $record->uri;
			if($record->watch == 1){
				$uri = $record->uri;
			}
		}
		$form['bekijken']['uri'] = array(
			'#type' => 'radios',
			'#title' => t('Selecteer een resource'),
			'#default_value' => $uri, // Default value moet geselecteerde URI worden
			'#options' => $options,
		);
		// Submit-knop
		$form['bekijken']['select'] = array (
			'#type' => 'submit',
			'#value' => t("Bekijken"),
			'#submit' => array('coap_resource_bekijken_form_select_submit'),
		);
		$form['bekijken']['delete'] = array (
			'#type' => 'submit',
			'#value' => t("Verwijderen"),
			'#submit' => array('coap_resource_bekijken_form_delete_submit'),
		);
	}
	
	//dpm($form);
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function coap_resource_bekijken_form_select_submit($form, $form_state) {
	global $user;
	$nid = $form_state['values']['nid'];
	
	// Variabele 'bekijken' van elk URI voor de user in de databank op 0 zetten
	$num_updated = db_update('coap_resource_users')
		->fields(array(
			'watch' => 0,
		))
		->condition('uid', $user->uid, '=')
		->condition('nid', $nid, '=')
		->execute();
	
	// Als observen opgestart wordt, variabele 'bekijken' op 1 zetten voor de gekozen URI
	$num_updated = db_update('coap_resource_users')
		->fields(array(
			'watch' => 1,
		))
		->condition('uid', $user->uid, '=')
		->condition('uri', $form_state['values']['uri'], '=')
		->execute();
}

function coap_resource_bekijken_form_delete_submit($form, $form_state) {
	global $user;
	
	// Variabele 'bekijken' van elk URI voor de user in de databank op 0 zetten
	// $num_updated = db_update('coap_resource_users')
		// ->fields(array(
			// 'watch' => 0,
		// ))
		// ->condition('uid', $user->uid, '=')
		// ->execute();
	
	// Als observen opgestart wordt, variabele 'bekijken' op 1 zetten voor de gekozen URI
	db_delete('coap_resource_users')
		->condition('uid', $user->uid, '=')
		->condition('uri', $form_state['values']['uri'], '=')
		->execute();
}

//////////////////////
// GET REQUEST FORM //
//////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function coap_resource_get_request_form(&$form, &$form_state) {
	
	// Submit-knop
	$form['wx_info']['get_request_submit'] = array (
		'#type' => 'submit',
		'#submit' => array('coap_resource_get_request_form_submit'),
		'#value' => t('GET'),
		'#prefix' => "<table id = 'requests' ><th colspan = '4' >Request methods</th><tr><td>",
		'#suffix' => "</td><td>",
		);
		
	//dpm($form);
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function coap_resource_get_request_form_submit($form, $form_state) {
	$handle = background_process_start('coap_resource_start_request', 'GET', $form_state['values']['nid']);
}


//////////////////////
// PUT REQUEST FORM //
//////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function coap_resource_put_request_form(&$form, &$form_state) {	
	// Invoer voor PUT
	$form['wx_info']['put_request_input'] = array (
		'#type' => 'textfield',
		'#title' => 'input',
		'#size' => 35,
		);
	
	// Submit-knop
	$form['wx_info']['put_request_submit'] = array (
		'#type' => 'submit',
		'#submit' => array('coap_resource_put_request_form_submit'),
		'#value' => t('PUT'),
		'#suffix' => "</td><td>",
		);
	
	//dpm($form);
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function coap_resource_put_request_form_submit($form, $form_state) {
	//$handle = background_process_start('coap_resource_start_request', 'PUT', $form_state['values']['nid'], $form_state['values']['put_request_input']);
	coap_resource_start_request('PUT', $form_state['values']['nid'], $form_state['values']['put_request_input']);
}


///////////////////////
// POST REQUEST FORM //
///////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function coap_resource_post_request_form(&$form, &$form_state) {	
	// Invoer voor POST
	$form['wx_info']['post_request_input'] = array (
		'#type' => 'textfield',
		'#title' => 'input',
		'#size' => 35,
		);
	
	// Submit-knop
	$form['wx_info']['post_request_submit'] = array (
		'#type' => 'submit',
		'#submit' => array('coap_resource_post_request_form_submit'),
		'#value' => t('POST'),
		'#suffix' => "</td><td>",
		);
		
	//dpm($form);
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function coap_resource_post_request_form_submit($form, $form_state) {
	$handle = background_process_start('coap_resource_start_request', 'POST', $form_state['values']['nid'], $form_state['values']['post_request_input']);
}


/////////////////////////
// DELETE REQUEST FORM //
/////////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function coap_resource_delete_request_form(&$form, &$form_state) {
	// Submit-knop
	$form['wx_info']['delete_request_submit'] = array (
		'#type' => 'submit',
		'#submit' => array('coap_resource_delete_request_form_submit'),
		'#value' => t('DELETE'),
		'#suffix' => "</td></tr>",
		);
	
	//dpm($form);	
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function coap_resource_delete_request_form_submit($form, $form_state) {
	$handle = background_process_start('coap_resource_start_request', 'DELETE', $form_state['values']['nid']);
}

/////////////////
// node insert //
/////////////////
function coap_resource_node_insert($node){
	global $user;
	if($node->type == 'coap_resource'){
		$uri = $node->coap_resource_uri_field['und'][0]['uri'];
		$result = db_select('coap_resource_resources', 'resources')
			->fields('resources', array('uri'))
			->condition('uri', $uri, '=')
			->execute();
		
		if($result->rowCount() == 0){
			$id = db_insert('coap_resource_resources')
				->fields(array(
					'uri' => $uri,
					'last_error' => 'none',
				))
				->execute();
		}
		
		$id = db_insert('coap_resource_users')
			->fields(array(
				'uid' => $user->uid,
				'uri' => $uri,
				'device' => 0,
				'nid' => $node->nid,
				'observe' => 0,
				'watch' => 1,
				'responded' => 0,
			))
			->execute();
	}
	else if($node->type == 'coap_device'){
		
	}
	
}

//////////////////////
// PRIVATE FUNCTIES //
//////////////////////

// Functie die wordt uitgevoerd als een ajax call wordt uitgevoerd naar /coap_resource/poll, geeft de laatste entry terug
function coap_resource_page_callback(){
	global $user;
	
	// bekeken URI bepalen
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uid', 'uri', 'watch', 'last_response', 'last_method', 'responded', 'response_type'))
		->condition('uid', $user->uid, '=')
		->condition('watch', 1, '=')
		->range(0,1);
	$result = $query->execute();
	$uri = '';
	foreach($result as $record){
		$uri = $record->uri;
		$method = $record->last_method;
		$response = $record->last_response;
		$responded = $record->responded;
		$response_type = $record->response_type;
	}
	
	// Laatste opvraging ophalen
	$query = db_select('coap_resource_values', 'coap_values');
	$query
		->fields('coap_values', array('hid', 'uid', 'timestamp', 'max_age', 'parsed_value', 'uri'))
		->condition('uri', $uri, '=')
		->condition('uid', $user->uid, '=')
		->orderBy('hid', 'DESC')
		->range(0,1);
	$result = $query->execute();
	
	// print een rij uit in tabelformaat zodat jQuery die kan gebruiken om in de tabel te stoppen
	foreach ($result as $record){
		$resources_query = db_select('coap_resource_resources', 'resources');
		$resources_query
			->fields('resources', array('uri', 'last_error'))
			->condition('uri', $record->uri, '=');
		$resources_result = $resources_query->execute();
		
		foreach($resources_result as $resources_record){
			$output = "<error>" . $resources_record->last_error . "</error><responded>" . $responded . "</responded><get_response>" . $response . "</get_response><method>" . $method . "</method><response_type>" . $response_type . "</response_type>";
			$hid = $record->hid;
			$timestamp = $record->timestamp;
			$temperatuur = $record->parsed_value;
			$max_age = $record->max_age;
			$output .= "<tr><td>" . $hid . "</td><td>" . $temperatuur . "</td><td>" . $max_age . "</td><td>" . $timestamp . "</td></tr>";
		}
	}
	if(!isset($output)){
		$query = db_select('coap_resource_resources', 'resources');
		$query
			->fields('resources', array('uri', 'last_error'))
			->condition('uri', $uri, '=');
		$result = $query->execute();
		
		if($result->rowCount() > 0){
			foreach($result as $record){
				$output = "<error>" . $record->last_error . "</error><responded>" . $responded . "</responded><get_response>" . $response . "</get_response><method>" . $method . "</method><response_type>" . $response_type . "</response_type>";
			}
		}
		else{
			$output = "no values";
		}
	}
	
	// Responded op false zetten
	$num_updated = db_update('coap_resource_users')
		->fields(array(
			'responded' => 0,
		))
		->condition('uid', $user->uid, '=')
		->execute();
	
	print $output;
	
	exit();
}

//	Change the interval that the polling mechanism is using for this user, this is a callback for /temperatuursensor/interval/%
function coap_resource_change_interval($interval){
	global $user;
	
	$seconds = intval($interval);
	$id = db_update('coap_resource_users')
			->fields(array(
				'polling_interval' => $seconds,
			))
			->condition('uid', $user->uid, '=')
			->execute();
}

// 	Start the observing mechanism for the resource with given URI
//	If the resource is not observable, the values will be retrieved periodically
function coap_resource_start_observing($uri){
	$pattern = '/([^\/]+)\/(.*)/i';
	if(preg_match($pattern, $uri, $matches)){
		$ip = $matches[1];
		$resource = $matches[2];
		
		// Determine if resource uses separate response
		$query = db_select('coap_resource_resources', 'resources');
		$query
			->fields('resources', array('uri', 'obs'))
			->condition('separate_response', 1, '=')
			->condition('uri', $uri, '=');
		$result = $query->execute();
		$separate_response = ($result->rowCount() > 0);
		
		$coap_factory = new CoAPMessageFactory('coap_resource', $ip, $resource, $separate_response);
		
		//	Get the record from the databse for given URI if it's observable, to check if the resource is observable
		$query = db_select('coap_resource_resources', 'resources');
		$query
			->fields('resources', array('uri', 'obs'))
			->condition('obs', 1, '=')
			->condition('uri', $uri, '=');
		$result = $query->execute();
		
		if($result->rowCount() > 0){
			// resource is observable
			$message = $coap_factory->create_observe_get_request($resource);
			$message->send_message();
		}
		else{
			// resource is not observable
			$message = $coap_factory->create_basic_get_request($resource);
			$query = db_select('coap_resource_users', 'users');
			$query
				->fields('users', array('uri', 'observe'))
				->condition('observe', 1, '=')
				->condition('uri', $uri, '=');
			$result = $query->execute();
			while($result->rowCount() > 0){
				$response_obj = $message->send_message();
				coap_resource_receive_notification($response_obj);
				sleep(5); // WAARDE NOG AANPASSEN NAAR EEN GEKOZEN WAARDE DOOR DE GEBRUIKER OF DE MAX AGE
				$result = $query->execute();
			}
		}
	}
}

//	Hook that is being called by CoAP library when observers of a given resource should stop observing
function coap_resource_stop_observers($ip, $resource){
	$num_updated = db_update('coap_resource_users')
			->fields(array(
				'observe' => 0,
			))
			->condition('uri', $ip . "/" . $resource, '=')
			->execute();
}

//	Returns the number of observers that are observing the given resource
function coap_resource_get_number_of_observers($ip, $resource){
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uri', 'observe'))
		->condition('uri', $ip . "/" . $resource, '=')
		->condition('observe', 1, '=');
	$result = $query->execute();
	return $result->rowCount();
}

// 	Creates and sends the CoAP message with given method and payload
//	IPv6-address and URI-path are extracted from the database
function coap_resource_start_request($method, $nid, $payload=''){
	global $user;
	
	//dpm(coap_library_string_to_hex_with_padding('.well-known/core'));
	//	Gets the URI for the resource that is selected by the user
	$result = db_select('coap_resource_users', 'users')
		->fields('users', array('uid', 'uri', 'nid', 'device', 'watch'))
		->condition('watch', 1, '=')
		->condition('uid', $user->uid, '=')
		->condition('device', 0, '=')
		->condition('nid', $nid, '=')
		->execute();
	foreach($result as $record){
		$uri = $record->uri;
	}
	
	//	Determine if resource uses separate response
	$query = db_select('coap_resource_resources', 'resources');
	$query
		->fields('resources', array('uri', 'separate_response'))
		->condition('separate_response', 1, '=')
		->condition('uri', $uri, '=');
	$result = $query->execute();
	$separate_response = ($result->rowCount() > 0);
	
	$pattern = '/([^\/]+)\/(.*)/i';
	if(preg_match($pattern, $uri, $matches)){
		//	Build message
		$coap_factory = new CoAPMessageFactory('coap_resource', $matches[1], $matches[2], $separate_response);
		switch ($method) {
			case 'GET':
				$coap_message = $coap_factory->create_basic_get_request($matches[2]);
				break;
			case 'PUT':
				$coap_message = $coap_factory->create_basic_put_request($matches[2]);
				break;
			case 'POST':
				$coap_message = $coap_factory->create_basic_post_request($matches[2]);
				break;
			case 'DELETE':
				$coap_message = $coap_factory->create_basic_delete_request($matches[2]);
				break;
		}
		if($payload != ''){
			$coap_message->set_payload(coap_library_string_to_hex_with_padding($payload));
		}
		
		$response_obj = null;
		
		if($method == "GET"){
			//	Get last value from the database for the given resource to check if value is still valid and use this value if it's still valid
			$cache_query = db_select('coap_resource_values', 'coap_resource_values');
			$cache_query
				->fields('coap_resource_values', array('uri', 'uid', 'hid', 'original_response', 'max_age', 'timestamp'))
				->condition('uri', $uri, '=')
				->condition('uid', $user->uid, '=')
				->orderBy('hid', 'DESC')
				->range(0,1);
			$cache_result = $cache_query->execute();
			foreach($cache_result as $cache_record){
				//	Check if the last value has a max age and if it has, check if the value is still valid
				if($cache_record->max_age != null && time()-strtotime($cache_record->timestamp) < intval($cache_record->max_age)){
					$response_obj = $coap_factory->create_message_with_given_hex_message($cache_record->original_response);
				}
			}
		}
		
		//	Get new value if previous isn't still valid or isn't GET
		if($response_obj == null){
			$response_obj = $coap_message->send_message();
			if($response_obj != null){
				//	Insert the response into the database to add to the history of responses
				coap_resource_insert_response_into_database($response_obj, $user->uid);
			}
		}
		
		if($response_obj != null){
			//	Insert the response into the database for the current user
			coap_resource_give_response_to_user($response_obj, $method);
		}
	}
}

// 	Creates and sends the CoAP message with given method for the given URI
function coap_resource_start_request_for_uri($method, $uri, $payload=''){

	$uri = str_replace('|', '/', $uri);
	global $user;
	
	//	Determine if resource uses separate response
	$query = db_select('coap_resource_resources', 'resources');
	$query
		->fields('resources', array('uri', 'separate_response'))
		->condition('separate_response', 1, '=')
		->condition('uri', $uri, '=');
	$result = $query->execute();
	$separate_response = ($result->rowCount() > 0);
	
	$pattern = '/([^\/]+)\/(.*)/i';
	if(preg_match($pattern, $uri, $matches)){
		//	Build message
		$coap_factory = new CoAPMessageFactory('coap_resource', $matches[1], $matches[2], $separate_response);
		switch ($method) {
			case 'GET':
				$coap_message = $coap_factory->create_basic_get_request($matches[2]);
				break;
			case 'PUT':
				$coap_message = $coap_factory->create_basic_put_request($matches[2]);
				break;
			case 'POST':
				$coap_message = $coap_factory->create_basic_post_request($matches[2]);
				break;
			case 'DELETE':
				$coap_message = $coap_factory->create_basic_delete_request($matches[2]);
				break;
		}
		if($payload != ''){
			$coap_message->set_payload(coap_library_string_to_hex_with_padding($payload));
		}
		
		$response_obj = null;
		
		if($method == "GET"){
			//	Get last value from the database for the given resource to check if value is still valid and use this value if it's still valid
			$cache_query = db_select('coap_resource_values', 'coap_resource_values');
			$cache_query
				->fields('coap_resource_values', array('uri', 'uid', 'hid', 'original_response', 'max_age', 'timestamp'))
				->condition('uri', $uri, '=')
				->condition('uid', $user->uid, '=')
				->orderBy('hid', 'DESC')
				->range(0,1);
			$cache_result = $cache_query->execute();
			foreach($cache_result as $cache_record){
				//	Check if the last value has a max age and if it has, check if the value is still valid
				if($cache_record->max_age != null && time()-strtotime($cache_record->timestamp) < intval($cache_record->max_age)){
					$response_obj = $coap_factory->create_message_with_given_hex_message($cache_record->original_response);
				}
			}
		}
		
		//	Get new value if previous isn't still valid or isn't GET
		if($response_obj == null){
			$response_obj = $coap_message->send_message();
			if($response_obj != null){
				//	Insert the response into the database to add to the history of responses
				coap_resource_insert_response_into_database($response_obj, $user->uid);
			}
		}
		
		if($response_obj != null){
			print "<uri>" . $uri . "</uri><method>" . $method . "</method><response>" . $response_obj->get_payload_text() . "</response>";
		}
	}
}

// Gets the temperature out of a payload (Celsius)
// Returns the original payload if temperature could not be parsed
function coap_resource_get_temperature($payload){
	$pattern = '/value\s+(.*)C/i';
	if(preg_match($pattern, $payload, $matches)){
		$temperature = $matches[1];
		return $temperature;
	}
	else{
		return $payload;
	}
}

//	Hook being called by the CoAP library if something went wrong when communicating with the resource with given ip and URI-path
function coap_resource_receive_error($error_message, $ip, $resource){
	$num_updated = db_update('coap_resource_resources')
			->fields(array(
				'last_error' => $error_message,
			))
			->condition('uri', $ip . "/" . $resource, '=')
			->execute();
}

//	Hook that gets called by the CoAP library when a notification arrives from a resource that is being observed
//	Adds the given response to the database for every interested user
function coap_resource_receive_notification($response_obj){
	global $user;
	
	//	Add the notification to the database for the current user
	coap_resource_insert_response_into_database($response_obj, $user->uid);
	
	//	Get interested user different from the current user
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uri', 'uid', 'observe'))
		->condition('uri', $response_obj->get_ip() . '/' . $response_obj->get_resource(), '=')
		->condition('observe', 1, '=')
		->condition('uid', $user->uid, '!=');
	$result = $query->execute();
	
	//	Add response to the database for every user that is interested, except from the current user
	foreach($result as $record){
		coap_resource_insert_response_into_database($response_obj, $record->uid);
	}
}

//	Adds the given response to the current user so the user can see the response (via database)
function coap_resource_give_response_to_user($response_obj, $request_method){
	global $user;
	
	if($response_obj != null){
		$num_updated = db_update('coap_resource_users')
		->fields(array(
			'responded' => 1,
			'last_method' => $request_method,
			'last_response' => $response_obj->get_payload_text(),
			'response_type' => $response_obj->get_message_code(),
		))
		->condition('uid', $user->uid, '=')
		->execute();
	}
	else{
		$num_updated = db_update('coap_resource_users')
		->fields(array(
			'responded' => 1,
			'last_method' => $request_method,
			'last_response' => 'no response returned',
		))
		->condition('uid', $user->uid, '=')
		->execute();
	}
}

//	Adds the given response to the database table with values for the given user
function coap_resource_insert_response_into_database($response_obj, $uid){
	//	Parsing values from response
	$max_age = $response_obj->get_max_age();
	$value = $response_obj->get_payload_text();
	$format = $response_obj->get_content_format();
	$content_type = $response_obj->get_message_code();
	if($format == 'text/plain'){
		$value = coap_resource_get_temperature($value);
	}
	$hid = db_insert('coap_resource_values')
		->fields(array(
			'payload' => $response_obj->get_payload(),
			'content_format' => $format,
			'original_response' => $response_obj->get_hex_message(),
			'parsed_value' => $value,
			'max_age' => $max_age,
			'uri' => ($response_obj->get_ip() . '/' . $response_obj->get_resource()),
			'uid' => $uid,
		))
		->execute();
}

//	Callback for AJAX call
//	Starts observe for the given URI
function coap_resource_handle_observing_for_uri($uri, $state){
	global $user;
	
	$uri = str_replace('|', '/', $uri); //	Put slashes back in the URI
	
	//	Get number of observers for the current URI
	$observe_result = db_select('coap_resource_users', 'users')
		->fields('users', array('uid', 'uri', 'observe'))
		->condition('uri', $uri, '=')
		->condition('device', 0, '=')
		->condition('observe', 1, '=')
		->execute();
	$num_observers = $observe_result->rowCount();
	
	//	Start observing the current URI if this user is interested and no one else was already observing
	if($state == "start" && $num_observers == 0){
		background_process_start('coap_resource_start_observing', $record->uri);
	}
	
	//	Store in database that this user is observing or not observing the current URI
	$num_updated = db_update('coap_resource_users')
		->fields(array(
			'observe' => ($start == "start" ? 1 : 0),
		))
		->condition('uri', $uri, '=')
		->condition('uid', $user->uid, '=')
		->condition('device', 0, '=')
		->execute();
	
	//	Get number of users that is still observing the current URI
	$observe_result = db_select('coap_resource_users', 'users')
		->fields('users', array('uid', 'uri', 'observe'))
		->condition('uri', $uri, '=')
		->condition('device', 0, '=')
		->condition('observe', 1, '=')
		->execute();
	
	//	Stop observing the URI if no one is interested anymore
	if($observe_result->rowCount() == 0){
		coap_library_stop_observing('coap_resource', $uri);
	}
	
	//	Return value for AJAX call
	echo "<uri>" . $uri . "</uri><response>success</response>";
}