<?php

require_once(drupal_get_path('module', 'coap_library') . '/coap_library_classes.inc');

/**
 * Implements hook_menu().
 * Creëert het pad waarnaar jQuery een ajax call kan uitvoeren en de callback-functie
 */
function coap_resource_menu() {
  $items = array();
  $items["coap_resource/poll"] = array(
    "title" => "Get last entry",
    "page callback" => "coap_resource_page_callback",
    "access callback" => true,
    "type" => MENU_CALLBACK
  );
  //coap_discovery_form
  
  
  return $items;
}


///////////
// BLOCK //
///////////

/**
 * Implements hook_block_info().
 * Geeft informatie over de block die de module aanbiedt
 */
function coap_resource_block_info() {
	$blocks['user_custom'] = array(
		'info' => t('Blok met mogelijkheid tot opvragen temperatuur en observeren van verloop van temperatuur'),
	);
	return $blocks;
}

/**
 * Implements hook_block_info().
 * Definieert de titel en inhoud van de block
 */
function coap_resource_block_view($delta='') {
	global $user;
	
	$block = null;
	$block['subject'] = 'Temperatuursensoren bevragen met het CoAP protocol';
	$block_content = null;
	
	// URI form
	$temp = drupal_get_form('uri_form');
	$block_content .= drupal_render($temp);
	
	// Observe form
	$temp = drupal_get_form('observe_form');
	$block_content .= drupal_render($temp);
	
	// Bekijken form
	$temp = drupal_get_form('bekijken_form');
	$block_content .= drupal_render($temp);
	
	// Table offering REST functionality
	$block_content .= "<table id = 'requests' ><th colspan = '4' >REST methods</th><tr><td>";
	
	// GET form
	$temp = drupal_get_form('get_request_form');
	$block_content .= drupal_render($temp) . "</td><td>";
	
	// PUT form
	$temp = drupal_get_form('put_request_form');
	$block_content .= drupal_render($temp) . "</td><td>";
	
	// POST form
	$temp = drupal_get_form('post_request_form');
	$block_content .= drupal_render($temp) . "</td><td>";
	
	// DELETE form
	$temp = drupal_get_form('delete_request_form');
	$block_content .= drupal_render($temp) . "</td></tr>";
	
	$block_content .= "<tr><td colspan = '4' ><label id = 'response' >Response: </label></td><tr><td colspan = '4' ><label id = 'response_type' >Response type: </label></td></tr></table>";
	
	
	$block_content .= "<img style = 'visibility:hidden;' src = '' id = 'errorimg' /><label id='error' ></label>"; // elementen om fouten te tonen
	
	// Te bekijken URI ophalen
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uid', 'uri', 'watch'))
		->condition('uid', $user->uid, '=')
		->condition('watch', 1, '=');
	$result = $query->execute();
	$empty = TRUE;
	foreach($result as $record){
		$empty = FALSE;
		$uri = $record->uri;
	}
	
	if(!$empty){
		// Tabel met geschiedenis van opvragingen(5 laatste)
		$query = db_select('coap_resource_values', 'coap_values');
		$query
			->fields('coap_values', array('hid', 'parsed_value', 'max_age', 'timestamp', 'uri', 'uid'))
			->condition('uri', $uri, '=')
			->condition('uid', $user->uid, '=')
			->orderBy('hid', 'DESC')
			->range(0,5);
		$result = $query->execute();
		$block_content .= "<table id='historytable' ><tr><th>Hid</th><th>Value</th><th>Max age</th><th>Timestamp</th></tr>";
		$nr = 1;
		foreach ($result as $record){ // voegt telkens een rij toe aan de tabel, waarbij de elementen een id met een rij-nr erna krijgen
			$value = $record->parsed_value;
			$hid = $record->hid;
			$max_age = $record->max_age;
			$timestamp = $record->timestamp;
			$block_content .= "<tr><td id='hid" . $nr . "' >" . $hid . "</td><td id='temperatuur" . $nr . "' >" . $value . "</td><td id='max_age" . $nr . "' >" . $max_age . "</td><td id='timestamp" . $nr . "' >" . $timestamp . "</td></tr>";
			$nr++;
		}
		while($nr <= 5){ // voegt telkens een rij toe aan de tabel, waarbij de elementen een id met een rij-nr erna krijgen
			$block_content .= "<tr><td id='hid" . $nr . "' >/</td><td id='temperatuur" . $nr . "' > </td><td id='max_age" . $nr . "' > </td><td id='timestamp" . $nr . "' > </td></tr>";
			$nr++;
		}
		$block_content .= "</table>";
		
		$block_content .= "<div id = 'grafiek' ></div>"; // Grafiek
	}
	
	$block['content'] = $block_content;
	drupal_add_js('https://www.google.com/jsapi'); // JavaScript bestand toevoegen
	drupal_add_js(drupal_get_path('module', 'coap_resource') . '/js/coap_resource.js'); // JavaScript bestand toevoegen
	return $block;
}

//////////////////
// BEKIJKEN FORM //
//////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function bekijken_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('Observe'),
	);
	
	global $user;
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uid', 'uri', 'watch'))
		->condition('uid', $user->uid,'=');
	$result = $query->execute();
	
	// Radio buttons om URI te selecteren
	if($result->rowCount() > 0){
		$options = array();
		foreach ($result as $record){
			$options[$record->uri] = $record->uri;
			if($record->watch == 1){
				$uri = $record->uri;
			}
		}
		$form['bekijken']['uri'] = array(
			'#type' => 'radios',
			'#title' => t('Selecteer een resource'),
			'#default_value' => $uri, // Default value moet geselecteerde URI worden
			'#options' => $options,
		);
	}
	
	// Submit-knop
	$form['bekijken']['submit'] = array (
		'#type' => 'submit',
		'#value' => t("Bekijken"),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function bekijken_form_submit($form, $form_state) {
	global $user;
	
	// Variabele 'bekijken' van elk URI voor de user in de databank op 0 zetten
	$num_updated = db_update('coap_resource_users')
		->fields(array(
			'watch' => 0,
		))
		->condition('uid', $user->uid, '=')
		->execute();
	
	// Als observen opgestart wordt, variabele 'bekijken' op 1 zetten voor de gekozen URI
	$num_updated = db_update('coap_resource_users')
		->fields(array(
			'watch' => 1,
		))
		->condition('uid', $user->uid, '=')
		->condition('uri', $form_state['values']['uri'], '=')
		->execute();
}

//////////////////////
// GET REQUEST FORM //
//////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function get_request_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('GET Request'),
	);
	
	// Submit-knop
	$form['wx_info']['temperatuur_udp_url_submit'] = array (
		'#type' => 'submit',
		'#value' => t('GET'),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function get_request_form_submit($form, $form_state) {
	$handle = background_process_start('start_request', 'GET');
}


//////////////////////
// PUT REQUEST FORM //
//////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function put_request_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('PUT Request'),
	);
	
	// Invoer voor PUT
	$form['wx_info']['put_request_input'] = array (
		'#type' => 'textfield',
		'#title' => 'input',
		'#size' => 35,
		);
	
	// Submit-knop
	$form['wx_info']['put_request_submit'] = array (
		'#type' => 'submit',
		'#value' => t('PUT'),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function put_request_form_submit($form, $form_state) {
	$handle = background_process_start('start_request', 'PUT', $form_state['values']['put_request_input']);
}


///////////////////////
// POST REQUEST FORM //
///////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function post_request_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('POST Request'),
	);
	
	// Invoer voor POST
	$form['wx_info']['post_request_input'] = array (
		'#type' => 'textfield',
		'#title' => 'input',
		'#size' => 35,
		);
	
	// Submit-knop
	$form['wx_info']['post_request_submit'] = array (
		'#type' => 'submit',
		'#value' => t('POST'),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function post_request_form_submit($form, $form_state) {
	$handle = background_process_start('start_request', 'POST', $form_state['values']['post_request_input']);
}


/////////////////////////
// DELETE REQUEST FORM //
/////////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function delete_request_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('DELETE Request'),
	);
	
	// Submit-knop
	$form['wx_info']['delete_request_submit'] = array (
		'#type' => 'submit',
		'#value' => t('DELETE'),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function delete_request_form_submit($form, $form_state) {
	$handle = background_process_start('start_request', 'DELETE');
}


//////////////
// URI FORM //
//////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function uri_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('URI form'),
	);
	
	// Eventuele fout
	$form['uri']['error'] = array(
		'#type' => 'item',
		'#markup' => variable_get('bad_uri', ''),
	);
	variable_del('bad_uri');
	
	// Invoer textbox voor URI
	$form['uri']['invoer'] = array(
		'#type' => 'textfield',
		'#title' => 'Geef een URI',
		'#default_value' => '',
	);
	
	// Submit-knop
	$form['uri']['submit'] = array (
		'#type' => 'submit',
		'#value' => t('Invoeren'),
	);
		
	$form['#action'] = '';
	
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function uri_form_submit($form, $form_state) {
	global $user;
	
	$pattern = '/([^\/]+)\/(.*)/i';
	if(preg_match($pattern, $form_state['values']['invoer'], $matches)){
		$query = db_select('coap_resource_resources', 'resources');
		$query
			->fields('resources', array('uri'))
			->condition('uri', $form_state['values']['invoer'], '=');
		$result = $query->execute();
		
		if($result->rowCount() == 0){
			$id = db_insert('coap_resource_resources')
				->fields(array(
					'uri' => $form_state['values']['invoer'],
					'observable' => 1,
					'last_error' => 'none',
				))
				->execute();
		}
		
		// Watch bij alle rijen van de user op nul zetten
		$num_updated = db_update('coap_resource_users')
			->fields(array(
				'watch' => 0,
			))
			->condition('uid', $user->uid, '=')
			->execute();
		
		// Watch van net toegevoegde URI op 1 zetten
		$id = db_insert('coap_resource_users')
			->fields(array(
				'uid' => $user->uid,
				'uri' => $form_state['values']['invoer'],
				'observe' => 0,
				'watch' => 1,
				'responded' => 0,
			))
			->execute();
	}
	else{
		variable_set('bad_uri', 'Er werd een ongeldige URI opgegeven.');
	}
}

//////////////////////
// OBSERVE FORM //
//////////////////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function observe_form($form_in, &$form_state) {
	// Titel van form
	$form['title'] = array (
		'#value' => t('Observe form'),
	);
	
	global $user;
	
	// Checkbox per observable resource
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uid', 'uri', 'observe'))
		->condition('uid', $user->uid,'=');
	$result = $query->execute();
	foreach ($result as $record){
		$form['observe'][$record->uri] = array(
			'#type' => 'checkbox',
			'#title' => $record->uri,
			'#default_value' => $record->observe,
		);
	}
	
	// Submit-knop
	$form['observe']['temperatuur_udp_url_submit'] = array (
		'#type' => 'submit',
		'#value' => t('Observe'),
		);
		
	$form['#action'] = '';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het formulier ingediend wordt
 */
function observe_form_submit($form, $form_state) {
	global $user;
	
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uid', 'uri'))
		->condition('uid', $user->uid, '=');
	$result = $query->execute();
	foreach ($result as $record){
		$observe_query = db_select('coap_resource_users', 'users');
		$observe_query
			->fields('users', array('uid', 'uri', 'observe'))
			->condition('uri', $record->uri, '=')
			->condition('observe', 1, '=');
		$observe_result = $observe_query->execute();
		$num_observers = $observe_result->rowCount();
	
		if($form_state['values'][$record->uri] != 0 && $num_observers == 0){
			background_process_start('start_observing', $record->uri);
		}
		$num_updated = db_update('coap_resource_users')
			->fields(array(
				'observe' => $form_state['values'][$record->uri],
			))
			->condition('uri', $record->uri, '=')
			->condition('uid', $user->uid, '=')
			->execute();
			
		$observe_query = db_select('coap_resource_users', 'users');
		$observe_query
			->fields('users', array('uid', 'uri', 'observe'))
			->condition('uri', $record->uri, '=')
			->condition('observe', 1, '=');
		$observe_result = $observe_query->execute();
		if($observe_result->rowCount() == 0){
			coap_library_stop_observing('coap_resource', $record->uri);
		}
	}
}


//////////////////////
// PRIVATE FUNCTIES //
//////////////////////

// Functie die wordt uitgevoerd als een ajax call wordt uitgevoerd naar /temperatuursensor/poll, geeft de laatste entry terug
function coap_resource_page_callback(){
	global $user;
	
	// bekeken URI bepalen
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uid', 'uri', 'watch', 'last_response', 'last_method', 'responded', 'response_type'))
		->condition('uid', $user->uid, '=')
		->condition('watch', 1, '=')
		->range(0,1);
	$result = $query->execute();
	$uri = '';
	foreach($result as $record){
		$uri = $record->uri;
		$method = $record->last_method;
		$response = $record->last_response;
		$responded = $record->responded;
		$response_type = $record->response_type;
	}
	
	// Laatste opvraging ophalen
	$query = db_select('coap_resource_values', 'coap_values');
	$query
		->fields('coap_values', array('hid', 'uid', 'timestamp', 'max_age', 'parsed_value', 'uri'))
		->condition('uri', $uri, '=')
		->condition('uid', $user->uid, '=')
		->orderBy('hid', 'DESC')
		->range(0,1);
	$result = $query->execute();
	
	// print een rij uit in tabelformaat zodat jQuery die kan gebruiken om in de tabel te stoppen
	foreach ($result as $record){
		$resources_query = db_select('coap_resource_resources', 'resources');
		$resources_query
			->fields('resources', array('uri', 'last_error'))
			->condition('uri', $record->uri, '=');
		$resources_result = $resources_query->execute();
		
		foreach($resources_result as $resources_record){
			$output = "<error>" . $resources_record->last_error . "</error><responded>" . $responded . "</responded><get_response>" . $response . "</get_response><method>" . $method . "</method><response_type>" . $response_type . "</response_type>";
			$hid = $record->hid;
			$timestamp = $record->timestamp;
			$temperatuur = $record->parsed_value;
			$max_age = $record->max_age;
			$output .= "<tr><td>" . $hid . "</td><td>" . $temperatuur . "</td><td>" . $max_age . "</td><td>" . $timestamp . "</td></tr>";
		}
	}
	if(!isset($output)){
		$query = db_select('coap_resource_resources', 'resources');
		$query
			->fields('resources', array('uri', 'last_error'))
			->condition('uri', $uri, '=');
		$result = $query->execute();
		
		if($result->rowCount() > 0){
			foreach($result as $record){
				$output = "<error>" . $record->last_error . "</error><responded>" . $responded . "</responded><get_response>" . $response . "</get_response><method>" . $method . "</method><response_type>" . $response_type . "</response_type>";
			}
		}
		else{
			$output = "no values";
		}
	}
	
	// Responded op false zetten
	$num_updated = db_update('coap_resource_users')
		->fields(array(
			'responded' => 0,
		))
		->condition('uid', $user->uid, '=')
		->execute();
	
	print $output;
}

function start_observing($uri){
	$pattern = '/([^\/]+)\/(.*)/i';
	if(preg_match($pattern, $uri, $matches)){
		$ip = $matches[1];
		$resource = $matches[2];
		
		$coap_factory = new CoAPMessageFactory('coap_resource', $ip, $resource);
		$message = $coap_factory->create_observe_get_request($resource);
		$message->send_message();
	}
}

function coap_resource_stop_observers($ip, $resource){
	$num_updated = db_update('coap_resource_users')
			->fields(array(
				'observe' => 0,
			))
			->condition('uri', $ip . "/" . $resource, '=')
			->execute();
}

function get_number_of_observers($ip, $resource){
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uri', 'observe'))
		->condition('uri', $ip . "/" . $resource, '=')
		->condition('observe', 1, '=');
	$result = $query->execute();
	return $result->rowCount();
}

//
function start_request($method, $payload=''){
	global $user;
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uid', 'uri', 'watch'))
		->condition('watch', 1, '=')
		->condition('uid', $user->uid, '=');
	$result = $query->execute();
	
	foreach($result as $record){
		$pattern = '/([^\/]+)\/(.*)/i';
		if(preg_match($pattern, $record->uri, $matches)){
			$coap_factory = new CoAPMessageFactory('coap_resource', $matches[1], $matches[2]);
			$coap_message = $coap_factory->create_message_with_header_and_token('CON', $method, 0);
			$coap_message->add_option(11, $matches[2]);
			if($payload != ''){
				$coap_message->add_payload($payload);
			}
			$response_obj = $coap_message->send_message();
			if($response_obj != null){
				$num_updated = db_update('coap_resource_users')
				->fields(array(
					'responded' => 1,
					'last_method' => $method,
					'last_response' => $response_obj->get_payload(),
					'response_type' => $response_obj->get_message_code(),
				))
				->condition('uid', $user->uid, '=')
				->execute();
			}
			else{
				$num_updated = db_update('coap_resource_users')
				->fields(array(
					'responded' => 1,
					'last_method' => $method,
					'last_response' => 'no response returned',
				))
				->condition('uid', $user->uid, '=')
				->execute();
			}
		}
	}
}

// Gets the temperature out of a payload (Celsius)
// Return the original payload if temperature could not be parsed
function coap_resource_get_temperature($payload){
	$pattern = '/value\s+(.*)C/i';
	if(preg_match($pattern, $payload, $matches)){
		$temperature = $matches[1];
		return $temperature;
	}
	else{
		return $payload;
	}
}

function coap_resource_receive_error($error_message, $ip, $resource){
	$num_updated = db_update('coap_resource_resources')
			->fields(array(
				'last_error' => $error_message,
			))
			->condition('uri', $ip . "/" . $resource, '=')
			->execute();
}

function coap_resource_receive_response($response_obj){
	$max_age = $response_obj->get_max_age();
	$value = $response_obj->get_payload();
	$format = $response_obj->get_content_format();
	if($format == 'text/plain'){
		$value = coap_resource_get_temperature($value);
	}
	variable_set('test', $response_obj->get_ip() . '/' . $response_obj->get_resource());
	
	global $user;
	variable_set('test', 'voor eerste insert');
	$hid = db_insert('coap_resource_values')
		->fields(array(
			'payload' => $response_obj->get_payload(),
			'content_format' => $format,
			'original_response' => $response_obj->getHexMessage(),
			'parsed_value' => $value,
			'max_age' => $max_age,
			'uri' => ($response_obj->get_ip() . '/' . $response_obj->get_resource()),
			'uid' => $user->uid,
		))
		->execute();
	variable_set('test', 'na eerste insert');
	
	$query = db_select('coap_resource_users', 'users');
	$query
		->fields('users', array('uri', 'uid', 'observe'))
		->condition('uri', $response_obj->get_ip() . '/' . $response_obj->get_resource(), '=')
		->condition('observe', 1, '=')
		->condition('uid', $user->uid, '!=');
	$result = $query->execute();
	
	foreach($result as $record){
		$hid = db_insert('coap_resource_values')
			->fields(array(
				'payload' => $response_obj->get_payload(),
				'content_format' => $format,
				'original_response' => $response_obj->getHexMessage(),
				'parsed_value' => $value,
				'max_age' => $max_age,
				'uri' => $response_obj->get_ip() . '/' . $response_obj->get_resource(),
				'uid' => $record->uid,
			))
			->execute();
	}
}