<?php

/**
 * Implements hook_menu().
 * Creëert het pad waarnaar jQuery een ajax call kan uitvoeren en de callback-functie
 */
function temperatuursensor_udp_menu() {
  $items = array();
  $items["observe/ajax"] = array(
    "title" => "Nieuwe temperatuur",
    "page callback" => "temperatuur_udp_page_callback",
    "access callback" => true,
    "type" => MENU_CALLBACK
  );
  return $items;
}

///////////
// BLOCK //
///////////

/**
 * Implements hook_block_info().
 * Geeft informatie over de block die de module aanbiedt
 */
function temperatuursensor_udp_block_info() {
	$blocks['user_custom'] = array(
		'info' => t('Blok met mogelijkheid tot opvragen temperatuur met udp-sockets als onderliggende technologie'),
	);
	return $blocks;
}

/**
 * Implements hook_block_info().
 * Definieert de titel en inhoud van de block
 */
function temperatuursensor_udp_block_view($delta='') {
	$block = null;
	$block['subject'] = 'Temperatuur via udp';
	$block_content = null;
	$current_observe = variable_get('observe_udp', null);
	$block_content .= "<label>Automatisch ophalen is momenteel " . (!isset($current_observe) || variable_get('observe_udp', null) == '0' ? 'niet ' : '') . " actief</label>";
	//HISTORY
	$query = db_select('temperaturen_udp', 'temperaturen_udp');
	$query
		->fields('temperaturen_udp', array('hid', 'response'))
		->orderBy('hid', 'DESC')
		->range(0,5);
	$result = $query->execute();
	$block_content .= "<table id='historytable_udp' ><tr><td>Hid</td><td>Response</td></tr>";
	$nr = 1;
	foreach ($result as $record){
		$hid = $record->hid;
		$origin = $record->response;
		$block_content .= "<tr><td id='hid_udp" . $nr . "' >" . $hid . "</td><td id='response_udp" . $nr . "' >" . $origin . "</td></tr>";
		$nr++;
	}
	$block_content .= "</table>";
	drupal_add_js(drupal_get_path('module', 'temperatuursensor_udp') .'/js/temperatuursensor_udp.js');
	$temp = drupal_get_form('temperatuur_udp_url_form');
	$block_content .= drupal_render($temp);
	$block['content'] = $block_content;
	return $block;
}

//////////
// FORM //
//////////

/**
 * Implements hook_form().
 * Voegt componenten toe aan de form
 */
function temperatuur_udp_url_form($form_in, &$form_state) {
	$form['wx_info_title'] = array (
		'#value' => t('Temperatuur'),
	);
	//$form['wx_info']['temperatuur_url'] = array (
	//	'#type' => 'textfield',
	//	'#size' => 20,
	//	'#maxlength' => 20,
	//);
	$options = array('Observe');
	$options_checked = array();
	$form['wx_info']['temperatuur_udp_url_checkbox'] = array (
		'#type' => 'checkbox',
		'#title' => t('Automatisch ophalen'),
		'#default_value' => variable_get('observe_udp', null),
		);
	$form['wx_info']['temperatuur_udp_url_submit'] = array (
		'#type' => 'submit',
		'#value' => t('Refresh'),
		);
	$form['#action'] = '/';
	return $form;
}

/**
 * Implements hook_form_submit().
 * functie die wordt uitgevoerd als het form ingediend wordt
 */
function temperatuur_udp_url_form_submit($form, $form_state) {
	//$url = trim($form_state['values']['temperatuur_url']);
	//variable_set('current_url', $url);
	variable_set('observe_udp', $form_state['values']['temperatuur_udp_url_checkbox']);
	if(variable_get('observe_udp', null) == '1'){
		$handle_observe = background_process_start('start_observing');
	}
	// $handle = background_process_start('check_validity_period');
}


//////////////////////
// PRIVATE FUNCTIES //
//////////////////////

// Functie die wordt uitgevoerd als een ajax call wordt uitgevoerd naar /observe/ajax, geeft de laatste entry terug
function temperatuur_udp_page_callback(){
	$query = db_select('temperaturen_udp', 'temperaturen_udp');
	$query
		->fields('temperaturen_udp', array('hid', 'response'))
		->orderBy('hid', 'DESC')
		->range(0,1);
	$result = $query->execute();
	$response = '<tr><td>';
	foreach ($result as $record){
		$hid = $record->hid;
		$origin = $record->response;
		$response .= $hid . "</td><td>" . $origin . "</td></tr>";
	}
	print $response;
}

// Functie die wacht tot max age is verstreken, om dan een nieuwe waarde op te halen, roept zichzelf op als er nog steeds automatisch opgehaald moet worden
function start_observing(){
	$observe = variable_get('observe_udp', null);
	$socket = fsockopen("udp://[2001:6a8:1d80:200::2]", 5683, $errno, $errstr); // udp-socket openen
	if (!$socket) {
		echo "$errstr ($errno)<br />\n";
	} else {
		$out = "40"; // Version(01) + type(00 voor Confirmable) + Token Length(0000) --> 01000000 --> 40
		$out .= "01"; // Code (00000001 voor GET) --> 00000001 --> 01
		$out .= generate_message_id(); // Message id --> 2 bytes --> 4 hexadecimalen
		$out .= "b3"; // Option Delta (1011 voor Path-URI) + Option Length (0011 bytes voor 'test') --> 10110011 --> b3
		$out .= "6f6273"; // Option value = 'obs' --> 6f6273
		$out .= "a0"; // Option Delta (1010 voor Path-URI) + Option Length (0000 bytes voor '') --> 10100000 --> a0
		$binary = pack("H*", $out); // hexadecimaal omzetten naar binair
		$returnvalue = fwrite($fp, $binary); // wegschrijven naar udp-socket
		if($returnvalue != FALSE){
			$response = fread($fp, 128); // lezen van udp-socket
		}
		else{
			echo "kon niet naar socket schrijven";
		}
	}
	while($observe == '1'){
		$hid = db_insert('temperaturen_udp')
				->fields(array(
					'response' => $response,
				))
				->execute();
		$response = fread($fp, 128); // lezen van udp-socket
		$observe = variable_get('observe_udp', null);
	}
	fclose($socket);
}