<?php
 
function custom_ct2_node_info() {
  return array(
      'custom_ct2' => array(
          'name' => t('custom_content_type2'),
          'base' => 'custom_ct2',
          'description' => t('A custom content type2.'),
          'has_title' => TRUE,
          'title_label' => t('custom_ct2 Title'),
          'locked' => FALSE,
      ),
  );
}
 
function custom_ct2_form($node, $form_state) {
  $type = node_type_get_type($node);
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#default_value' => !empty($node->title) ? $node->title : '',
    '#required' => TRUE, '#weight' => -5
  );
 
  return $form;
}

//function custom_ct2_form_alter(&$form, &$form_state, $form_id) {
//  if ($form_id == 'custom_content_type_node_form') {
//    //dsm($form); // This function is available via Devel module. Here, it shows you the contents of $form in a structured manner, so that you know where to make the change to add a button.
//    // Add code here to add button in the form etc.
//	$form['submit'] = array(
//      '#type' => 'submit', 
//      '#value' => t('Fetch'), 
//      '#weight' => 19,
//    );
//  }
//}